<?php
/**
 * new_tstaat
 *
 * @author cr
 * @created Fri, 03 Nov 2017 12:50:32 +0100
 */

use JTL\Update\IMigration;
use JTL\Update\Migration;

/**
 * Class Migration_20171103125032
 */
class Migration_20171103125032 extends Migration implements IMigration
{
    protected $author      = 'cr';
    protected $description = 're-create the table tstaat, transfer to valid ISO 3166-2';

    /**
     * @inheritDoc
     */
    public function up()
    {
        $this->execute('DROP TABLE IF EXISTS `tstaat`');
        $this->execute(
            "CREATE TABLE IF NOT EXISTS `tstaat` (
                  `kStaat` int(10) unsigned NOT NULL AUTO_INCREMENT
                , `cLandIso` varchar(2) NOT NULL COMMENT 'should be value of ISO 3166-1'
                , `cName` varchar(255) NOT NULL COMMENT 'full name of the state or province'
                , `cCode` varchar(10) NOT NULL COMMENT 'should be value of ISO 3166-2'
                , PRIMARY KEY (`kStaat`)
                , KEY `cLandIso` (`cLandIso`)
                , KEY `cName` (`cName`)
                , KEY `cCode` (`cCode`)
            ) ENGINE InnoDB CHARSET utf8 COLLATE utf8_unicode_ci"
        );
        /*US military post offices*/
        $this->execute(
            "INSERT INTO
                `tstaat` (`cLandIso`, `cName`, `cCode`)
            VALUES
                  ('US','Armed Forces Africa','AF')
                , ('US','Armed Forces Americas','AA')
                , ('US','Armed Forces Canada','AC')
                , ('US','Armed Forces Europe','AE')
                , ('US','Armed Forces Middle East','AM')
                , ('US','Armed Forces Pacific','AP')"
        );
        /*United States Of America*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('US', 'US-AL', 'Alabama')
                , ('US', 'US-AK', 'Alaska')
                , ('US', 'US-AZ', 'Arizona')
                , ('US', 'US-AR', 'Arkansas')
                , ('US', 'US-CA', 'California')
                , ('US', 'US-CO', 'Colorado')
                , ('US', 'US-CT', 'Connecticut')
                , ('US', 'US-DE', 'Delaware')
                , ('US', 'US-FL', 'Florida')
                , ('US', 'US-GA', 'Georgia')
                , ('US', 'US-HI', 'Hawaii')
                , ('US', 'US-ID', 'Idaho')
                , ('US', 'US-IL', 'Illinois')
                , ('US', 'US-IN', 'Indiana')
                , ('US', 'US-IA', 'Iowa')
                , ('US', 'US-KS', 'Kansas')
                , ('US', 'US-KY', 'Kentucky')
                , ('US', 'US-LA', 'Louisiana')
                , ('US', 'US-ME', 'Maine')
                , ('US', 'US-MD', 'Maryland')
                , ('US', 'US-MA', 'Massachusetts')
                , ('US', 'US-MI', 'Michigan')
                , ('US', 'US-MN', 'Minnesota')
                , ('US', 'US-MS', 'Mississippi')
                , ('US', 'US-MO', 'Missouri')
                , ('US', 'US-MT', 'Montana')
                , ('US', 'US-NE', 'Nebraska')
                , ('US', 'US-NV', 'Nevada')
                , ('US', 'US-NH', 'New Hampshire')
                , ('US', 'US-NJ', 'New Jersey')
                , ('US', 'US-NM', 'New Mexico')
                , ('US', 'US-NY', 'New York')
                , ('US', 'US-NC', 'North Carolina')
                , ('US', 'US-ND', 'North Dakota')
                , ('US', 'US-OH', 'Ohio')
                , ('US', 'US-OK', 'Oklahoma')
                , ('US', 'US-OR', 'Oregon')
                , ('US', 'US-PA', 'Pennsylvania')
                , ('US', 'US-RI', 'Rhode Island')
                , ('US', 'US-SC', 'South Carolina')
                , ('US', 'US-SD', 'South Dakota')
                , ('US', 'US-TN', 'Tennessee')
                , ('US', 'US-TX', 'Texas')
                , ('US', 'US-UT', 'Utah')
                , ('US', 'US-VT', 'Vermont')
                , ('US', 'US-VA', 'Virginia')
                , ('US', 'US-WA', 'Washington')
                , ('US', 'US-WV', 'West Virginia')
                , ('US', 'US-WI', 'Wisconsin')
                , ('US', 'US-WY', 'Wyoming')
                , ('US', 'US-DC', 'District of Columbia')
                , ('US', 'US-AS', 'American Samoa')
                , ('US', 'US-GU', 'Guam')
                , ('US', 'US-MP', 'Northern Mariana Islands')
                , ('US', 'US-PR', 'Puerto Rico')
                , ('US', 'US-UM', 'United States Minor Outlying Islands')
                , ('US', 'US-VI', 'Virgin Islands, U.S.')"
        );
        /*Canada*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('CA', 'CA-AB', 'Alberta')
                , ('CA', 'CA-BC', 'British Columbia')
                , ('CA', 'CA-MB', 'Manitoba')
                , ('CA', 'CA-NB', 'New Brunswick')
                , ('CA', 'CA-NL', 'Newfoundland and Labrador')
                , ('CA', 'CA-NS', 'Nova Scotia')
                , ('CA', 'CA-ON', 'Ontario')
                , ('CA', 'CA-PE', 'Prince Edward Island')
                , ('CA', 'CA-QC', 'Quebec')
                , ('CA', 'CA-SK', 'Saskatchewan')
                , ('CA', 'CA-NT', 'Northwest Territories')
                , ('CA', 'CA-NU', 'Nunavut')
                , ('CA', 'CA-YT', 'Yukon')"
        );
        /*Germany*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('DE', 'DE-BW', 'Baden-Württemberg')
                , ('DE', 'DE-BY', 'Bayern')
                , ('DE', 'DE-BE', 'Berlin')
                , ('DE', 'DE-BB', 'Brandenburg')
                , ('DE', 'DE-HB', 'Bremen')
                , ('DE', 'DE-HH', 'Hamburg')
                , ('DE', 'DE-HE', 'Hessen')
                , ('DE', 'DE-MV', 'Mecklenburg-Vorpommern')
                , ('DE', 'DE-NI', 'Niedersachsen')
                , ('DE', 'DE-NW', 'Nordrhein-Westfalen')
                , ('DE', 'DE-RP', 'Rheinland-Pfalz')
                , ('DE', 'DE-SL', 'Saarland')
                , ('DE', 'DE-SN', 'Sachsen')
                , ('DE', 'DE-ST', 'Sachsen-Anhalt')
                , ('DE', 'DE-SH', 'Schleswig-Holstein')
                , ('DE', 'DE-TH', 'Thüringen')"
        );
        /*Austria*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('AT', 'AT-1', 'Burgenland')
                , ('AT', 'AT-2', 'Kärnten')
                , ('AT', 'AT-3', 'Niederösterreich')
                , ('AT', 'AT-4', 'Oberösterreich')
                , ('AT', 'AT-5', 'Salzburg')
                , ('AT', 'AT-6', 'Steiermark')
                , ('AT', 'AT-7', 'Tirol')
                , ('AT', 'AT-8', 'Vorarlberg')
                , ('AT', 'AT-9', 'Wien')"
        );
        /*Switzerland*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('CH', 'CH-AG', 'Aargau')
                , ('CH', 'CH-AR', 'Appenzell Ausserrhoden')
                , ('CH', 'CH-AI', 'Appenzell Innerrhoden')
                , ('CH', 'CH-BL', 'Basel-Landschaft')
                , ('CH', 'CH-BS', 'Basel-Stadt')
                , ('CH', 'CH-BE', 'Bern,')
                , ('CH', 'CH-FR', 'Freiburg')
                , ('CH', 'CH-GE', 'Genève')
                , ('CH', 'CH-GL', 'Glarus')
                , ('CH', 'CH-GR', 'Graubünden')
                , ('CH', 'CH-JU', 'Jura')
                , ('CH', 'CH-LU', 'Luzern')
                , ('CH', 'CH-NE', 'Neuchâtel')
                , ('CH', 'CH-NW', 'Nidwalden')
                , ('CH', 'CH-OW', 'Obwalden')
                , ('CH', 'CH-SG', 'Sankt Gallen')
                , ('CH', 'CH-SH', 'Schaffhausen')
                , ('CH', 'CH-SZ', 'Schwyz')
                , ('CH', 'CH-SO', 'Solothurn')
                , ('CH', 'CH-TG', 'Thurgau')
                , ('CH', 'CH-TI', 'Ticino')
                , ('CH', 'CH-UR', 'Uri')
                , ('CH', 'CH-VS', 'Wallis')
                , ('CH', 'CH-VD', 'Vaud')
                , ('CH', 'CH-ZG', 'Zug')
                , ('CH', 'CH-ZH', 'Zürich')"
        );
        /*Spain*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                  ('ES', 'ES-C', 'A Coruña')
                , ('ES', 'ES-VI', 'Araba')
                , ('ES', 'ES-AB', 'Albacete')
                , ('ES', 'ES-A', 'Alicante')
                , ('ES', 'ES-AL', 'Almería')
                , ('ES', 'ES-O', 'Asturias')
                , ('ES', 'ES-AV', 'Ávila')
                , ('ES', 'ES-BA', 'Badajoz')
                , ('ES', 'ES-PM', 'Baleares')
                , ('ES', 'ES-B', 'Barcelona')
                , ('ES', 'ES-BU', 'Burgos')
                , ('ES', 'ES-CC', 'Cáceres')
                , ('ES', 'ES-CA', 'Cádiz')
                , ('ES', 'ES-S', 'Cantabria')
                , ('ES', 'ES-CS', 'Castellón')
                , ('ES', 'ES-CR', 'Ciudad Real')
                , ('ES', 'ES-CO', 'Córdoba')
                , ('ES', 'ES-CU', 'Cuenca')
                , ('ES', 'ES-GI', 'Gerona')
                , ('ES', 'ES-GR', 'Granada')
                , ('ES', 'ES-GU', 'Guadalajara')
                , ('ES', 'ES-SS', 'Gipuzkoa')
                , ('ES', 'ES-H', 'Huelva')
                , ('ES', 'ES-HU', 'Huesca')
                , ('ES', 'ES-J', 'Jaén')
                , ('ES', 'ES-LO', 'La Rioja')
                , ('ES', 'ES-GC', 'Las Palmas')
                , ('ES', 'ES-LE', 'León')
                , ('ES', 'ES-L', 'Lérida')
                , ('ES', 'ES-LU', 'Lugo')
                , ('ES', 'ES-M', 'Madrid')
                , ('ES', 'ES-MA', 'Málaga')
                , ('ES', 'ES-MU', 'Murcia')
                , ('ES', 'ES-NA', 'Navarra')
                , ('ES', 'ES-OR', 'Orense')
                , ('ES', 'ES-P', 'Palencia')
                , ('ES', 'ES-PO', 'Pontevedra')
                , ('ES', 'ES-SA',  'Salamanca')
                , ('ES', 'ES-TF', 'Santa Cruz de Tenerife')
                , ('ES', 'ES-SG', 'Segovia')
                , ('ES', 'ES-SE', 'Sevilla')
                , ('ES', 'ES-SO', 'Soria')
                , ('ES', 'ES-T', 'Tarragona')
                , ('ES', 'ES-TE', 'Teruel')
                , ('ES', 'ES-TO', 'Toledo')
                , ('ES', 'ES-V', 'Valencia')
                , ('ES', 'ES-VA', 'Valladolid')
                , ('ES', 'ES-BI', 'Bizkaia')
                , ('ES', 'ES-ZA', 'Zamora')
                , ('ES', 'ES-Z', 'Zaragoza')"
        );
        /*Fance*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('FR', 'FR-ARA', 'Auvergne-Rhône-Alpes')
              , ('FR', 'FR-BFC', 'Bourgogne-Franche-Comté')
              , ('FR', 'FR-BRE', 'Bretagne')
              , ('FR', 'FR-CVL', 'Centre-Val de Loire')
              , ('FR', 'FR-COR', 'Corse')
              , ('FR', 'FR-GES', 'Grand Est')
              , ('FR', 'FR-HDF', 'Hauts-de-France')
              , ('FR', 'FR-IDF', 'Île-de-France')
              , ('FR', 'FR-NOR', 'Normandie')
              , ('FR', 'FR-NAQ', 'Nouvelle-Aquitaine')
              , ('FR', 'FR-OCC', 'Occitanie')
              , ('FR', 'FR-PDL', 'Pays de la Loire')
              , ('FR', 'FR-PAC', 'Provence-Alpes-Côte d\'Azur')"
        );
        /*France Overseas departments*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('FR', 'FR-GP', 'Guadeloupe')
              , ('FR', 'FR-GF', 'Guyane')
              , ('FR', 'FR-MQ', 'Martinique')
              , ('FR', 'FR-YT', 'Mayotte')
              , ('FR', 'FR-RE', 'La Réunion')"
        );
        /*former metropolitan departments (before Jan. 1st, 2016)*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('FR', 'FR-01', 'Ain')
              , ('FR', 'FR-02', 'Aisne')
              , ('FR', 'FR-03', 'Allier')
              , ('FR', 'FR-04', 'Alpes-de-Haute-Provence')
              , ('FR', 'FR-06', 'Alpes-Maritimes')
              , ('FR', 'FR-07', 'Ardèche')
              , ('FR', 'FR-08', 'Ardennes')
              , ('FR', 'FR-09', 'Ariège')
              , ('FR', 'FR-10', 'Aube')
              , ('FR', 'FR-11', 'Aude')
              , ('FR', 'FR-12', 'Aveyron')
              , ('FR', 'FR-67', 'Bas-Rhin')
              , ('FR', 'FR-13', 'Bouches-du-Rhône')
              , ('FR', 'FR-14', 'Calvados')
              , ('FR', 'FR-15', 'Cantal')
              , ('FR', 'FR-16', 'Charente')
              , ('FR', 'FR-17', 'Charente-Maritime')
              , ('FR', 'FR-18', 'Cher')
              , ('FR', 'FR-19', 'Corrèze')
              , ('FR', 'FR-2A', 'Corse-du-Sud')
              , ('FR', 'FR-21', 'Côte-d\'Or')
              , ('FR', 'FR-22', 'Côtes-d\'Armor')
              , ('FR', 'FR-23', 'Creuse')
              , ('FR', 'FR-79', 'Deux-Sèvres')
              , ('FR', 'FR-24', 'Dordogne')
              , ('FR', 'FR-25', 'Doubs')
              , ('FR', 'FR-26', 'Drôme')
              , ('FR', 'FR-91', 'Essonne')
              , ('FR', 'FR-27', 'Eure')
              , ('FR', 'FR-28', 'Eure-et-Loir')
              , ('FR', 'FR-29', 'Finistère')
              , ('FR', 'FR-30', 'Gard')
              , ('FR', 'FR-32', 'Gers')
              , ('FR', 'FR-33', 'Gironde')
              , ('FR', 'FR-2B', 'Haute-Corse')
              , ('FR', 'FR-31', 'Haute-Garonne')
              , ('FR', 'FR-43', 'Haute-Loire')
              , ('FR', 'FR-52', 'Haute-Marne')
              , ('FR', 'FR-05', 'Hautes-Alpes')
              , ('FR', 'FR-70', 'Haute-Saône')
              , ('FR', 'FR-74', 'Haute-Savoie')
              , ('FR', 'FR-65', 'Hautes-Pyrénées')
              , ('FR', 'FR-87', 'Haute-Vienne')
              , ('FR', 'FR-68', 'Haut-Rhin')
              , ('FR', 'FR-92', 'Hauts-de-Seine')
              , ('FR', 'FR-34', 'Hérault')
              , ('FR', 'FR-35', 'Ille-et-Vilaine')
              , ('FR', 'FR-36', 'Indre')
              , ('FR', 'FR-37', 'Indre-et-Loire')
              , ('FR', 'FR-38', 'Isère')
              , ('FR', 'FR-39', 'Jura')
              , ('FR', 'FR-40', 'Landes')
              , ('FR', 'FR-42', 'Loire')
              , ('FR', 'FR-44', 'Loire-Atlantique')
              , ('FR', 'FR-45', 'Loiret')
              , ('FR', 'FR-41', 'Loir-et-Cher')
              , ('FR', 'FR-46', 'Lot')
              , ('FR', 'FR-47', 'Lot-et-Garonne')
              , ('FR', 'FR-48', 'Lozère')
              , ('FR', 'FR-49', 'Maine-et-Loire')
              , ('FR', 'FR-50', 'Manche')
              , ('FR', 'FR-51', 'Marne')
              , ('FR', 'FR-53', 'Mayenne')
              , ('FR', 'FR-54', 'Meurthe-et-Moselle')
              , ('FR', 'FR-55', 'Meuse')
              , ('FR', 'FR-56', 'Morbihan')
              , ('FR', 'FR-57', 'Moselle')
              , ('FR', 'FR-58', 'Nièvre')
              , ('FR', 'FR-59', 'Nord')
              , ('FR', 'FR-60', 'Oise')
              , ('FR', 'FR-61', 'Orne')
              , ('FR', 'FR-75', 'Paris')
              , ('FR', 'FR-62', 'Pas-de-Calais')
              , ('FR', 'FR-63', 'Puy-de-Dôme')
              , ('FR', 'FR-64', 'Pyrénées-Atlantiques')
              , ('FR', 'FR-66', 'Pyrénées-Orientales')
              , ('FR', 'FR-69', 'Rhône[3]')
              , ('FR', 'FR-71', 'Saône-et-Loire')
              , ('FR', 'FR-72', 'Sarthe')
              , ('FR', 'FR-73', 'Savoie')
              , ('FR', 'FR-77', 'Seine-et-Marne')
              , ('FR', 'FR-76', 'Seine-Maritime')
              , ('FR', 'FR-93', 'Seine-Saint-Denis')
              , ('FR', 'FR-80', 'Somme')
              , ('FR', 'FR-81', 'Tarn')
              , ('FR', 'FR-82', 'Tarn-et-Garonne')
              , ('FR', 'FR-90', 'Territoire de Belfort')
              , ('FR', 'FR-94', 'Val-de-Marne')
              , ('FR', 'FR-95', 'Val-d\'Oise')
              , ('FR', 'FR-83', 'Var')
              , ('FR', 'FR-84', 'Vaucluse')
              , ('FR', 'FR-85', 'Vendée')
              , ('FR', 'FR-86', 'Vienne')
              , ('FR', 'FR-88', 'Vosges')
              , ('FR', 'FR-89', 'Yonne')
              , ('FR', 'FR-78', 'Yvelines')"
        );
        /*Romania*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('RO', 'RO-AB','Alba')
              , ('RO', 'RO-AR','Arad')
              , ('RO', 'RO-AG','Argeș')
              , ('RO', 'RO-BC','Bacău')
              , ('RO', 'RO-BH','Bihor')
              , ('RO', 'RO-BN','Bistrița-Năsăud')
              , ('RO', 'RO-BT','Botoșani')
              , ('RO', 'RO-BV','Brașov')
              , ('RO', 'RO-BR','Brăila')
              , ('RO', 'RO-BZ','Buzău')
              , ('RO', 'RO-CS','Caraș-Severin')
              , ('RO', 'RO-CL','Călărași')
              , ('RO', 'RO-CJ','Cluj')
              , ('RO', 'RO-CT','Constanța')
              , ('RO', 'RO-CV','Covasna')
              , ('RO', 'RO-DB','Dâmbovița')
              , ('RO', 'RO-DJ','Dolj')
              , ('RO', 'RO-GL','Galați')
              , ('RO', 'RO-GR','Giurgiu')
              , ('RO', 'RO-GJ','Gorj')
              , ('RO', 'RO-HR','Harghita')
              , ('RO', 'RO-HD','Hunedoara')
              , ('RO', 'RO-IL','Ialomița')
              , ('RO', 'RO-IS','Iași')
              , ('RO', 'RO-IF','Ilfov')
              , ('RO', 'RO-MM','Maramureș')
              , ('RO', 'RO-MH','Mehedinți')
              , ('RO', 'RO-MS','Mureș')
              , ('RO', 'RO-NT','Neamț')
              , ('RO', 'RO-OT','Olt')
              , ('RO', 'RO-PH','Prahova')
              , ('RO', 'RO-SM','Satu Mare')
              , ('RO', 'RO-SJ','Sălaj')
              , ('RO', 'RO-SB','Sibiu')
              , ('RO', 'RO-SV','Suceava')
              , ('RO', 'RO-TR','Teleorman')
              , ('RO', 'RO-TM','Timiș')
              , ('RO', 'RO-TL','Tulcea')
              , ('RO', 'RO-VS','Vaslui')
              , ('RO', 'RO-VL','Vâlcea')
              , ('RO', 'RO-VN','Vrancea')
              , ('RO', 'RO-B','București')"
        );
        /*Finland*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('FI', 'FI-01', 'Åland')
              , ('FI', 'FI-02', 'South Karelia')
              , ('FI', 'FI-03', 'Southern Ostrobothnia')
              , ('FI', 'FI-04', 'Southern Savonia')
              , ('FI', 'FI-05', 'Kainuu')
              , ('FI', 'FI-06', 'Tavastia Proper')
              , ('FI', 'FI-07', 'Central Ostrobothnia')
              , ('FI', 'FI-08', 'Central Finland')
              , ('FI', 'FI-09', 'Kymenlaakso')
              , ('FI', 'FI-10', 'Lapland')
              , ('FI', 'FI-11', 'Pirkanmaa')
              , ('FI', 'FI-12', 'Ostrobothnia')
              , ('FI', 'FI-13', 'North Karelia')
              , ('FI', 'FI-14', 'Northern Ostrobothnia')
              , ('FI', 'FI-15', 'Northern Savonia')
              , ('FI', 'FI-16', 'Päijänne Tavastia')
              , ('FI', 'FI-17', 'Satakunta')
              , ('FI', 'FI-18', 'Uusimaa')
              , ('FI', 'FI-19', 'Southwest Finland')"
        );
        /*Estonia*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('EE', 'EE-37', 'Harju')
              , ('EE', 'EE-39', 'Hiiu')
              , ('EE', 'EE-44', 'Ida-Viru')
              , ('EE', 'EE-49', 'Jõgeva')
              , ('EE', 'EE-51', 'Järva')
              , ('EE', 'EE-57', 'Lääne')
              , ('EE', 'EE-59', 'Lääne-Viru')
              , ('EE', 'EE-65', 'Põlva')
              , ('EE', 'EE-67', 'Pärnu')
              , ('EE', 'EE-70', 'Rapla')
              , ('EE', 'EE-74', 'Saare')
              , ('EE', 'EE-78', 'Tartu')
              , ('EE', 'EE-82', 'Valga')
              , ('EE', 'EE-84', 'Viljandi')
              , ('EE', 'EE-86', 'Võru')"
        );
        /*Latvia (Lettland)*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('LV', 'LV-DGV', 'Daugavpils')
              , ('LV', 'LV-JEL', 'Jelgava')
              , ('LV', 'LV-JKB', 'Jēkabpils')
              , ('LV', 'LV-JUR', 'Jūrmala')
              , ('LV', 'LV-LPX', 'Liepāja')
              , ('LV', 'LV-REZ', 'Rēzekne')
              , ('LV', 'LV-RIX', 'Rīga')
              , ('LV', 'LV-VMR', 'Valmiera')
              , ('LV', 'LV-VEN', 'Ventspils')"
        );

        /*Latvia (Lettland), municipality codes*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('LV', 'LV-001', 'Aglonas novads (Aglona)')
              , ('LV', 'LV-002', 'Aizkraukles novads (Aizkraukle)')
              , ('LV', 'LV-003', 'Aizputes novads (Aizpute)')
              , ('LV', 'LV-004', 'Aknīstes novads (Aknīste)')
              , ('LV', 'LV-005', 'Alojas novads (Aloja)')
              , ('LV', 'LV-006', 'Alsungas novads (Alsunga)')
              , ('LV', 'LV-007', 'Alūksnes novads (Alūksne)')
              , ('LV', 'LV-008', 'Amatas novads (Amata)')
              , ('LV', 'LV-009', 'Apes novads (Ape)')
              , ('LV', 'LV-010', 'Auces novads (Auce)')
              , ('LV', 'LV-011', 'Ādažu novads (Ādaži)')
              , ('LV', 'LV-012', 'Babītes novads (Babīte)')
              , ('LV', 'LV-013', 'Baldones novads (Baldone)')
              , ('LV', 'LV-014', 'Baltinavas novads (Baltinava)')
              , ('LV', 'LV-015', 'Balvu novads (Balvi)')
              , ('LV', 'LV-016', 'Bauskas novads (Bauska)')
              , ('LV', 'LV-017', 'Beverīnas novads (Beverīna)')
              , ('LV', 'LV-018', 'Brocēnu novads (Brocēni)')
              , ('LV', 'LV-019', 'Burtnieku novads (Burtnieki)')
              , ('LV', 'LV-020', 'Carnikavas novads (Carnikava)')
              , ('LV', 'LV-021', 'Cesvaines novads (Cesvaine)')
              , ('LV', 'LV-022', 'Cēsu novads (Cēsis)')
              , ('LV', 'LV-023', 'Ciblas novads (Cibla)')
              , ('LV', 'LV-024', 'Dagdas novads (Dagda)')
              , ('LV', 'LV-025', 'Daugavpils novads (Daugavpils)')
              , ('LV', 'LV-026', 'Dobeles novads (Dobele)')
              , ('LV', 'LV-027', 'Dundagas novads (Dundaga)')
              , ('LV', 'LV-028', 'Durbes novads (Durbe)')
              , ('LV', 'LV-029', 'Engures novads (Engure)')
              , ('LV', 'LV-030', 'Ērgļu novads (Ērgļi)')
              , ('LV', 'LV-031', 'Garkalnes novads (Garkalne)')
              , ('LV', 'LV-032', 'Grobiņas novads (Grobiņa)')
              , ('LV', 'LV-033', 'Gulbenes novads (Gulbene)')
              , ('LV', 'LV-034', 'Iecavas novads (Iecava)')
              , ('LV', 'LV-035', 'Ikšķiles novads (Ikšķile)')
              , ('LV', 'LV-036', 'Ilūkstes novads (Ilūkste)')
              , ('LV', 'LV-037', 'Inčukalna novads (Inčukalns)')
              , ('LV', 'LV-038', 'Jaunjelgavas novads (Jaunjelgava)')
              , ('LV', 'LV-039', 'Jaunpiebalgas novads (Jaunpiebalga)')
              , ('LV', 'LV-040', 'Jaunpils novads (Jaunpils)')
              , ('LV', 'LV-041', 'Jelgavas novads (Jelgava)')
              , ('LV', 'LV-042', 'Jēkabpils novads (Jēkabpils)')
              , ('LV', 'LV-043', 'Kandavas novads (Kandava)')
              , ('LV', 'LV-044', 'Kārsavas novads (Kārsava)')
              , ('LV', 'LV-045', 'Kocēnu novads (Kocēni)')
              , ('LV', 'LV-046', 'Kokneses novads (Koknese)')
              , ('LV', 'LV-047', 'Krāslavas novads (Krāslava)')
              , ('LV', 'LV-048', 'Krimuldas novads (Krimulda)')
              , ('LV', 'LV-049', 'Krustpils novads (Krustpils)')
              , ('LV', 'LV-050', 'Kuldīgas novads (Kuldīga)')
              , ('LV', 'LV-051', 'Ķeguma novads (Ķegums)')
              , ('LV', 'LV-052', 'Ķekavas novads (Ķekava)')
              , ('LV', 'LV-053', 'Lielvārdes novads (Lielvārde)')
              , ('LV', 'LV-054', 'Limbažu novads (Limbaži)')
              , ('LV', 'LV-055', 'Līgatnes novads (Līgatne)')
              , ('LV', 'LV-056', 'Līvānu novads (Līvāni)')
              , ('LV', 'LV-057', 'Lubānas novads (Lubāna)')
              , ('LV', 'LV-058', 'Ludzas novads (Ludza)')
              , ('LV', 'LV-059', 'Madonas novads (Madona)')
              , ('LV', 'LV-060', 'Mazsalacas novads (Mazsalaca)')
              , ('LV', 'LV-061', 'Mālpils novads (Mālpils)')
              , ('LV', 'LV-062', 'Mārupes novads (Mārupe)')
              , ('LV', 'LV-063', 'Mērsraga novads (Mērsrags)')
              , ('LV', 'LV-064', 'Naukšēnu novads (Naukšēni)')
              , ('LV', 'LV-065', 'Neretas novads (Nereta)')
              , ('LV', 'LV-066', 'Nīcas novads (Nīca)')
              , ('LV', 'LV-067', 'Ogres novads (Ogre)')
              , ('LV', 'LV-068', 'Olaines novads (Olaine)')
              , ('LV', 'LV-069', 'Ozolnieku novads (Ozolnieki)')
              , ('LV', 'LV-070', 'Pārgaujas novads (Pārgauja)')
              , ('LV', 'LV-071', 'Pāvilostas novads (Pāvilosta)')
              , ('LV', 'LV-072', 'Pļaviņu novads (Pļaviņas)')
              , ('LV', 'LV-073', 'Preiļu novads (Preiļi)')
              , ('LV', 'LV-074', 'Priekules novads (Priekule)')
              , ('LV', 'LV-075', 'Priekuļu novads (Priekuļi)')
              , ('LV', 'LV-076', 'Raunas novads (Rauna)')
              , ('LV', 'LV-077', 'Rēzeknes novads (Rēzekne)')
              , ('LV', 'LV-078', 'Riebiņu novads (Riebiņi)')
              , ('LV', 'LV-079', 'Rojas novads (Roja)')
              , ('LV', 'LV-080', 'Ropažu novads (Ropaži)')
              , ('LV', 'LV-081', 'Rucavas novads (Rucava)')
              , ('LV', 'LV-082', 'Rugāju novads (Rugāji)')
              , ('LV', 'LV-083', 'Rundāles novads (Rundāle)')
              , ('LV', 'LV-084', 'Rūjienas novads (Rūjiena)')
              , ('LV', 'LV-085', 'Salas novads (Sala)')
              , ('LV', 'LV-086', 'Salacgrīvas novads (Salacgrīva)')
              , ('LV', 'LV-087', 'Salaspils novads (Salaspils)')
              , ('LV', 'LV-088', 'Saldus novads (Saldus)')
              , ('LV', 'LV-089', 'Saulkrastu novads (Saulkrasti)')
              , ('LV', 'LV-090', 'Sējas novads (Sēja)')
              , ('LV', 'LV-091', 'Siguldas novads (Sigulda)')
              , ('LV', 'LV-092', 'Skrīveru novads (Skrīveri)')
              , ('LV', 'LV-093', 'Skrundas novads (Skrunda)')
              , ('LV', 'LV-094', 'Smiltenes novads (Smiltene)')
              , ('LV', 'LV-095', 'Stopiņu novads (Stopiņi)')
              , ('LV', 'LV-096', 'Strenču novads (Strenči)')
              , ('LV', 'LV-097', 'Talsu novads (Talsi)')
              , ('LV', 'LV-098', 'Tērvetes novads (Tērvete)')
              , ('LV', 'LV-099', 'Tukuma novads (Tukums)')
              , ('LV', 'LV-100', 'Vaiņodes novads (Vaiņode)')
              , ('LV', 'LV-101', 'Valkas novads (Valka)')
              , ('LV', 'LV-102', 'Varakļānu novads (Varakļāni)')
              , ('LV', 'LV-103', 'Vārkavas novads (Vārkava)')
              , ('LV', 'LV-104', 'Vecpiebalgas novads (Vecpiebalga)')
              , ('LV', 'LV-105', 'Vecumnieku novads (Vecumnieki)')
              , ('LV', 'LV-106', 'Ventspils novads (Ventspils)')
              , ('LV', 'LV-107', 'Viesītes novads (Viesīte)')
              , ('LV', 'LV-108', 'Viļakas novads (Viļaka)')
              , ('LV', 'LV-109', 'Viļānu novads (Viļāni)')
              , ('LV', 'LV-110', 'Zilupes novads (Zilupe)')"
        );
        /*Lithuania (Littauen)*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('LT', 'LT-AL', 'Alytaus Apskritis')
              , ('LT', 'LT-KU', 'Kauno Apskritis')
              , ('LT', 'LT-KL', 'Klaipėdos Apskritis')
              , ('LT', 'LT-MR', 'Marijampolės Apskritis')
              , ('LT', 'LT-PN', 'Panevėžio Apskritis')
              , ('LT', 'LT-SA', 'Šiaulių Apskritis')
              , ('LT', 'LT-TA', 'Tauragės Apskritis')
              , ('LT', 'LT-TE', 'Telšių Apskritis')
              , ('LT', 'LT-UT', 'Utenos Apskritis')
              , ('LT', 'LT-VL', 'Vilniaus Apskritis')"
        );
        /*Brazil*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('BR', 'BR-DF', 'Distrito Federal')
              , ('BR', 'BR-AC', 'Acre')
              , ('BR', 'BR-AL', 'Alagoas')
              , ('BR', 'BR-AP', 'Amapá')
              , ('BR', 'BR-AM', 'Amazonas')
              , ('BR', 'BR-BA', 'Bahia')
              , ('BR', 'BR-CE', 'Ceará')
              , ('BR', 'BR-ES', 'Espírito Santo')
              , ('BR', 'BR-GO', 'Goiás')
              , ('BR', 'BR-MA', 'Maranhão')
              , ('BR', 'BR-MT', 'Mato Grosso')
              , ('BR', 'BR-MS', 'Mato Grosso do Sul')
              , ('BR', 'BR-MG', 'Minas Gerais')
              , ('BR', 'BR-PA', 'Pará')
              , ('BR', 'BR-PB', 'Paraíba')
              , ('BR', 'BR-PR', 'Paraná')
              , ('BR', 'BR-PE', 'Pernambuco')
              , ('BR', 'BR-PI', 'Piauí')
              , ('BR', 'BR-RJ', 'Rio de Janeiro')
              , ('BR', 'BR-RN', 'Rio Grande do Norte')
              , ('BR', 'BR-RS', 'Rio Grande do Sul')
              , ('BR', 'BR-RO', 'Rondônia')
              , ('BR', 'BR-RR', 'Roraima')
              , ('BR', 'BR-SC', 'Santa Catarina')
              , ('BR', 'BR-SP', 'São Paulo')
              , ('BR', 'BR-SE', 'Sergipe')
              , ('BR', 'BR-TO', 'Tocantins')"
        );
        /*India*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('IN', 'IN-AP', 'Andhra Pradesh')
              , ('IN', 'IN-AR', 'Arunachal Pradesh')
              , ('IN', 'IN-AS', 'Assam')
              , ('IN', 'IN-BR', 'Bihar')
              , ('IN', 'IN-CT', 'Chhattisgarh')
              , ('IN', 'IN-GA', 'Goa')
              , ('IN', 'IN-GJ', 'Gujarat')
              , ('IN', 'IN-HR', 'Haryana')
              , ('IN', 'IN-HP', 'Himachal Pradesh')
              , ('IN', 'IN-JK', 'Jammu and Kashmir')
              , ('IN', 'IN-JH', 'Jharkhand')
              , ('IN', 'IN-KA', 'Karnataka')
              , ('IN', 'IN-KL', 'Kerala')
              , ('IN', 'IN-MP', 'Madhya Pradesh')
              , ('IN', 'IN-MH', 'Maharashtra')
              , ('IN', 'IN-MN', 'Manipur')
              , ('IN', 'IN-ML', 'Meghalaya')
              , ('IN', 'IN-MZ', 'Mizoram')
              , ('IN', 'IN-NL', 'Nagaland')
              , ('IN', 'IN-OR', 'Odisha')
              , ('IN', 'IN-PB', 'Punjab')
              , ('IN', 'IN-RJ', 'Rajasthan')
              , ('IN', 'IN-SK', 'Sikkim')
              , ('IN', 'IN-TN', 'Tamil Nadu')
              , ('IN', 'IN-TG', 'Telangana')
              , ('IN', 'IN-TR', 'Tripura')
              , ('IN', 'IN-UT', 'Uttarakhand')
              , ('IN', 'IN-UP', 'Uttar Pradesh')
              , ('IN', 'IN-WB', 'West Bengal')
              , ('IN', 'IN-AN', 'Andaman and Nicobar Islands')
              , ('IN', 'IN-CH', 'Chandigarh')
              , ('IN', 'IN-DN', 'Dadra and Nagar Haveli')
              , ('IN', 'IN-DD', 'Daman and Diu')
              , ('IN', 'IN-DL', 'Delhi')
              , ('IN', 'IN-LD', 'Lakshadweep')
              , ('IN', 'IN-PY', 'Puducherry')"
        );
        /*Argentina*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('AR', 'AR-C', 'Ciudad Autónoma de Buenos Aires')
              , ('AR', 'AR-B', 'Buenos Aires')
              , ('AR', 'AR-K', 'Catamarca')
              , ('AR', 'AR-H', 'Chaco')
              , ('AR', 'AR-U', 'Chubut')
              , ('AR', 'AR-X', 'Córdoba')
              , ('AR', 'AR-W', 'Corrientes')
              , ('AR', 'AR-E', 'Entre Ríos')
              , ('AR', 'AR-P', 'Formosa')
              , ('AR', 'AR-Y', 'Jujuy')
              , ('AR', 'AR-L', 'La Pampa')
              , ('AR', 'AR-F', 'La Rioja')
              , ('AR', 'AR-M', 'Mendoza')
              , ('AR', 'AR-N', 'Misiones')
              , ('AR', 'AR-Q', 'Neuquén')
              , ('AR', 'AR-R', 'Río Negro')
              , ('AR', 'AR-A', 'Salta')
              , ('AR', 'AR-J', 'San Juan')
              , ('AR', 'AR-D', 'San Luis')
              , ('AR', 'AR-Z', 'Santa Cruz')
              , ('AR', 'AR-S', 'Santa Fe')
              , ('AR', 'AR-G', 'Santiago del Estero')
              , ('AR', 'AR-V', 'Tierra del Fuego')
              , ('AR', 'AR-T', 'Tucumán')"
        );
        /*Italy*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('IT', 'IT-AG', 'Agrigento')
              , ('IT', 'IT-AL', 'Alessandria')
              , ('IT', 'IT-AN', 'Ancona')
              , ('IT', 'IT-AO', 'Aosta')
              , ('IT', 'IT-AR', 'Arezzo')
              , ('IT', 'IT-AP', 'Ascoli Piceno')
              , ('IT', 'IT-AT', 'Asti')
              , ('IT', 'IT-AV', 'Avellino')
              , ('IT', 'IT-BA', 'Bari')
              , ('IT', 'IT-BT', 'Barletta-Andria-Trani')
              , ('IT', 'IT-BL', 'Belluno')
              , ('IT', 'IT-BN', 'Benevento')
              , ('IT', 'IT-BG', 'Bergamo')
              , ('IT', 'IT-BI', 'Biella')
              , ('IT', 'IT-BO', 'Bologna')
              , ('IT', 'IT-BZ', 'Bolzano')
              , ('IT', 'IT-BS', 'Brescia')
              , ('IT', 'IT-BR', 'Brindisi')
              , ('IT', 'IT-CA', 'Cagliari')
              , ('IT', 'IT-CL', 'Caltanissetta')
              , ('IT', 'IT-CB', 'Campobasso')
              , ('IT', 'IT-CI', 'Carbonia-Iglesias')
              , ('IT', 'IT-CE', 'Caserta')
              , ('IT', 'IT-CT', 'Catania')
              , ('IT', 'IT-CZ', 'Catanzaro')
              , ('IT', 'IT-CH', 'Chieti')
              , ('IT', 'IT-CO', 'Como')
              , ('IT', 'IT-CS', 'Cosenza')
              , ('IT', 'IT-CR', 'Cremona')
              , ('IT', 'IT-KR', 'Crotone')
              , ('IT', 'IT-CN', 'Cuneo')
              , ('IT', 'IT-EN', 'Enna')
              , ('IT', 'IT-FM', 'Fermo')
              , ('IT', 'IT-FE', 'Ferrara')
              , ('IT', 'IT-FI', 'Firenze')
              , ('IT', 'IT-FG', 'Foggia')
              , ('IT', 'IT-FC', 'Forlì-Cesena')
              , ('IT', 'IT-FR', 'Frosinone')
              , ('IT', 'IT-GE', 'Genova')
              , ('IT', 'IT-GO', 'Gorizia')
              , ('IT', 'IT-GR', 'Grosseto')
              , ('IT', 'IT-IM', 'Imperia')
              , ('IT', 'IT-IS', 'Isernia')
              , ('IT', 'IT-SP', 'La Spezia')
              , ('IT', 'IT-AQ', 'L\'Aquila')
              , ('IT', 'IT-LT', 'Latina')
              , ('IT', 'IT-LE', 'Lecce')
              , ('IT', 'IT-LC', 'Lecco')
              , ('IT', 'IT-LI', 'Livorno')
              , ('IT', 'IT-LO', 'Lodi')
              , ('IT', 'IT-LU', 'Lucca')
              , ('IT', 'IT-MC', 'Macerata')
              , ('IT', 'IT-MN', 'Mantova')
              , ('IT', 'IT-MS', 'Massa and Carrara')
              , ('IT', 'IT-MT', 'Matera')
              , ('IT', 'IT-VS', 'Medio Campidano')
              , ('IT', 'IT-ME', 'Messina')
              , ('IT', 'IT-MI', 'Milano')
              , ('IT', 'IT-MO', 'Modena')
              , ('IT', 'IT-MB', 'Monza and Brianza')
              , ('IT', 'IT-NA', 'Napoli')
              , ('IT', 'IT-NO', 'Novara')
              , ('IT', 'IT-NU', 'Nuoro')
              , ('IT', 'IT-OG', 'Ogliastra')
              , ('IT', 'IT-OT', 'Olbia-Tempio')
              , ('IT', 'IT-OR', 'Oristano')
              , ('IT', 'IT-PD', 'Padova')
              , ('IT', 'IT-PA', 'Palermo')
              , ('IT', 'IT-PR', 'Parma')
              , ('IT', 'IT-PV', 'Pavia')
              , ('IT', 'IT-PG', 'Perugia')
              , ('IT', 'IT-PU', 'Pesaro and Urbino')
              , ('IT', 'IT-PE', 'Pescara')
              , ('IT', 'IT-PC', 'Piacenza')
              , ('IT', 'IT-PI', 'Pisa')
              , ('IT', 'IT-PT', 'Pistoia')
              , ('IT', 'IT-PN', 'Pordenone')
              , ('IT', 'IT-PZ', 'Potenza')
              , ('IT', 'IT-PO', 'Prato')
              , ('IT', 'IT-RG', 'Ragusa')
              , ('IT', 'IT-RA', 'Ravenna')
              , ('IT', 'IT-RC', 'Reggio Calabria')
              , ('IT', 'IT-RE', 'Reggio Emilia')
              , ('IT', 'IT-RI', 'Rieti')
              , ('IT', 'IT-RN', 'Rimini')
              , ('IT', 'IT-RM', 'Roma')
              , ('IT', 'IT-RO', 'Rovigo')
              , ('IT', 'IT-SA', 'Salerno')
              , ('IT', 'IT-SS', 'Sassari')
              , ('IT', 'IT-SV', 'Savona')
              , ('IT', 'IT-SI', 'Siena')
              , ('IT', 'IT-SR', 'Siracusa')
              , ('IT', 'IT-SO', 'Sondrio')
              , ('IT', 'IT-TA', 'Taranto')
              , ('IT', 'IT-TE', 'Teramo')
              , ('IT', 'IT-TR', 'Terni')
              , ('IT', 'IT-TO', 'Torino')
              , ('IT', 'IT-TP', 'Trapani')
              , ('IT', 'IT-TN', 'Trento')
              , ('IT', 'IT-TV', 'Treviso')
              , ('IT', 'IT-TS', 'Trieste')
              , ('IT', 'IT-UD', 'Udine')
              , ('IT', 'IT-VA', 'Varese')
              , ('IT', 'IT-VE', 'Venezia')
              , ('IT', 'IT-VB', 'Verbano-Cusio-Ossola')
              , ('IT', 'IT-VC', 'Vercelli')
              , ('IT', 'IT-VR', 'Verona')
              , ('IT', 'IT-VV', 'Vibo Valentia')
              , ('IT', 'IT-VI', 'Vicenza')
              , ('IT', 'IT-VT', 'Viterbo')"
        );
        /*Japan*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('JP', 'JP-23', 'Aichi')
              , ('JP', 'JP-05', 'Akita')
              , ('JP', 'JP-02', 'Aomori')
              , ('JP', 'JP-38', 'Ehime')
              , ('JP', 'JP-21', 'Gifu')
              , ('JP', 'JP-10', 'Gunma')
              , ('JP', 'JP-34', 'Hiroshima')
              , ('JP', 'JP-01', 'Hokkaido')
              , ('JP', 'JP-18', 'Fukui')
              , ('JP', 'JP-40', 'Fukuoka')
              , ('JP', 'JP-07', 'Fukushima')
              , ('JP', 'JP-28', 'Hyogo')
              , ('JP', 'JP-08', 'Ibaraki')
              , ('JP', 'JP-17', 'Ishikawa')
              , ('JP', 'JP-03', 'Iwate')
              , ('JP', 'JP-37', 'Kagawa')
              , ('JP', 'JP-46', 'Kagoshima')
              , ('JP', 'JP-14', 'Kanagawa')
              , ('JP', 'JP-39', 'Kochi')
              , ('JP', 'JP-43', 'Kumamoto')
              , ('JP', 'JP-26', 'Kyoto')
              , ('JP', 'JP-24', 'Mie')
              , ('JP', 'JP-04', 'Miyagi')
              , ('JP', 'JP-45', 'Miyazaki')
              , ('JP', 'JP-20', 'Nagano')
              , ('JP', 'JP-42', 'Nagasaki')
              , ('JP', 'JP-29', 'Nara')
              , ('JP', 'JP-15', 'Niigata')
              , ('JP', 'JP-44', 'Oita')
              , ('JP', 'JP-33', 'Okayama')
              , ('JP', 'JP-47', 'Okinawa')
              , ('JP', 'JP-27', 'Osaka')
              , ('JP', 'JP-41', 'Saga')
              , ('JP', 'JP-11', 'Saitama')
              , ('JP', 'JP-25', 'Shiga')
              , ('JP', 'JP-32', 'Shimane')
              , ('JP', 'JP-22', 'Shizuoka')
              , ('JP', 'JP-12', 'Chiba')
              , ('JP', 'JP-09', 'Tochigi')
              , ('JP', 'JP-36', 'Tokushima')
              , ('JP', 'JP-13', 'Tokyo')
              , ('JP', 'JP-31', 'Tottori')
              , ('JP', 'JP-16', 'Toyama')
              , ('JP', 'JP-30', 'Wakayama')
              , ('JP', 'JP-06', 'Yamagata')
              , ('JP', 'JP-35', 'Yamaguchi')
              , ('JP', 'JP-19', 'Yamanashi')"
        );
        /*Mexico*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('MX', 'MX-CMX', 'Mexican Federal District')
              , ('MX', 'MX-AGU', 'Aguascalientes')
              , ('MX', 'MX-BCN', 'Baja California')
              , ('MX', 'MX-BCS', 'Baja California Sur')
              , ('MX', 'MX-CAM', 'Campeche')
              , ('MX', 'MX-COA', 'Coahuila')
              , ('MX', 'MX-COL', 'Colima')
              , ('MX', 'MX-CHP', 'Chiapas')
              , ('MX', 'MX-CHH', 'Chihuahua')
              , ('MX', 'MX-DUR', 'Durango')
              , ('MX', 'MX-GUA', 'Guanajuato')
              , ('MX', 'MX-GRO', 'Guerrero')
              , ('MX', 'MX-HID', 'Hidalgo')
              , ('MX', 'MX-JAL', 'Jalisco')
              , ('MX', 'MX-MEX', 'México')
              , ('MX', 'MX-MIC', 'Michoacán')
              , ('MX', 'MX-MOR', 'Morelos')
              , ('MX', 'MX-NAY', 'Nayarit')
              , ('MX', 'MX-NLE', 'Nuevo León')
              , ('MX', 'MX-OAX', 'Oaxaca')
              , ('MX', 'MX-PUE', 'Puebla')
              , ('MX', 'MX-QUE', 'Querétaro')
              , ('MX', 'MX-ROO', 'Quintana Roo')
              , ('MX', 'MX-SLP', 'San Luis Potosí')
              , ('MX', 'MX-SIN', 'Sinaloa')
              , ('MX', 'MX-SON', 'Sonora')
              , ('MX', 'MX-TAB', 'Tabasco')
              , ('MX', 'MX-TAM', 'Tamaulipas')
              , ('MX', 'MX-TLA', 'Tlaxcala')
              , ('MX', 'MX-VER', 'Veracruz')
              , ('MX', 'MX-YUC', 'Yucatán')
              , ('MX', 'MX-ZAC', 'Zacatecas')"
        );
        /*Thailand*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('TH', 'TH-10', 'Krung Thep Maha Nakhon [Bangkok]')
              , ('TH', 'TH-S', 'Phatthaya')
              , ('TH', 'TH-37', 'Amnat Charoen')
              , ('TH', 'TH-15', 'Ang Thong')
              , ('TH', 'TH-38', 'Bueng Kan')
              , ('TH', 'TH-31', 'Buri Ram')
              , ('TH', 'TH-24', 'Chachoengsao')
              , ('TH', 'TH-18', 'Chai Nat')
              , ('TH', 'TH-36', 'Chaiyaphum')
              , ('TH', 'TH-22', 'Chanthaburi')
              , ('TH', 'TH-50', 'Chiang Mai')
              , ('TH', 'TH-57', 'Chiang Rai')
              , ('TH', 'TH-20', 'Chon Buri')
              , ('TH', 'TH-86', 'Chumphon')
              , ('TH', 'TH-46', 'Kalasin')
              , ('TH', 'TH-62', 'Kamphaeng Phet')
              , ('TH', 'TH-71', 'Kanchanaburi')
              , ('TH', 'TH-40', 'Khon Kaen')
              , ('TH', 'TH-81', 'Krabi')
              , ('TH', 'TH-52', 'Lampang')
              , ('TH', 'TH-51', 'Lamphun')
              , ('TH', 'TH-42', 'Loei')
              , ('TH', 'TH-16', 'Lop Buri')
              , ('TH', 'TH-58', 'Mae Hong Son')
              , ('TH', 'TH-44', 'Maha Sarakham')
              , ('TH', 'TH-49', 'Mukdahan')
              , ('TH', 'TH-26', 'Nakhon Nayok')
              , ('TH', 'TH-73', 'Nakhon Pathom')
              , ('TH', 'TH-48', 'Nakhon Phanom')
              , ('TH', 'TH-30', 'Nakhon Ratchasima')
              , ('TH', 'TH-60', 'Nakhon Sawan')
              , ('TH', 'TH-80', 'Nakhon Si Thammarat')
              , ('TH', 'TH-55', 'Nan')
              , ('TH', 'TH-96', 'Narathiwat')
              , ('TH', 'TH-39', 'Nong Bua Lam Phu')
              , ('TH', 'TH-43', 'Nong Khai')
              , ('TH', 'TH-12', 'Nonthaburi')
              , ('TH', 'TH-13', 'Pathum Thani')
              , ('TH', 'TH-94', 'Pattani')
              , ('TH', 'TH-82', 'Phangnga')
              , ('TH', 'TH-93', 'Phatthalung')
              , ('TH', 'TH-56', 'Phayao')
              , ('TH', 'TH-67', 'Phetchabun')
              , ('TH', 'TH-76', 'Phetchaburi')
              , ('TH', 'TH-66', 'Phichit')
              , ('TH', 'TH-65', 'Phitsanulok')
              , ('TH', 'TH-54', 'Phrae')
              , ('TH', 'TH-14', 'Phra Nakhon Si Ayutthaya')
              , ('TH', 'TH-83', 'Phuket')
              , ('TH', 'TH-25', 'Prachin Buri')
              , ('TH', 'TH-77', 'Prachuap Khiri Khan')
              , ('TH', 'TH-85', 'Ranong')
              , ('TH', 'TH-70', 'Ratchaburi')
              , ('TH', 'TH-21', 'Rayong')
              , ('TH', 'TH-45', 'Roi Et')
              , ('TH', 'TH-27', 'Sa Kaeo')
              , ('TH', 'TH-47', 'Sakon Nakhon')
              , ('TH', 'TH-11', 'Samut Prakan')
              , ('TH', 'TH-74', 'Samut Sakhon')
              , ('TH', 'TH-75', 'Samut Songkhram')
              , ('TH', 'TH-19', 'Saraburi')
              , ('TH', 'TH-91', 'Satun')
              , ('TH', 'TH-17', 'Sing Buri')
              , ('TH', 'TH-33', 'Si Sa Ket')
              , ('TH', 'TH-90', 'Songkhla')
              , ('TH', 'TH-64', 'Sukhothai')
              , ('TH', 'TH-72', 'Suphan Buri')
              , ('TH', 'TH-84', 'Surat Thani')
              , ('TH', 'TH-32', 'Surin')
              , ('TH', 'TH-63', 'Tak')
              , ('TH', 'TH-92', 'Trang')
              , ('TH', 'TH-23', 'Trat')
              , ('TH', 'TH-34', 'Ubon Ratchathani')
              , ('TH', 'TH-41', 'Udon Thani')
              , ('TH', 'TH-61', 'Uthai Thani')
              , ('TH', 'TH-53', 'Uttaradit')
              , ('TH', 'TH-95', 'Yala')
              , ('TH', 'TH-35', 'Yasothon')"
        );
        /*additionals*/
        /*Netherlands*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('NL', 'NL-DR', 'Drenthe')
              , ('NL', 'NL-FL', 'Flevoland')
              , ('NL', 'NL-FR', 'Fryslân')
              , ('NL', 'NL-GE', 'Gelderland')
              , ('NL', 'NL-GR', 'Groningen')
              , ('NL', 'NL-LI', 'Limburg')
              , ('NL', 'NL-NB', 'Noord-Brabant')
              , ('NL', 'NL-NH', 'Noord-Holland')
              , ('NL', 'NL-OV', 'Overijssel')
              , ('NL', 'NL-UT', 'Utrecht')
              , ('NL', 'NL-ZE', 'Zeeland')
              , ('NL', 'NL-ZH', 'Zuid-Holland')"
        );
        /*Belgium*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('BE', 'BE-VAN', 'Antwerpen')
              , ('BE', 'BE-WBR', 'Brabant wallon')
              , ('BE', 'BE-WHT', 'Hainaut')
              , ('BE', 'BE-WLG', 'Liège')
              , ('BE', 'BE-VLI', 'Limburg')
              , ('BE', 'BE-WLX', 'Luxembourg')
              , ('BE', 'BE-WNA', 'Namur')
              , ('BE', 'BE-VOV', 'Oost-Vlaanderen')
              , ('BE', 'BE-VBR', 'Vlaams-Brabant')
              , ('BE', 'BE-VWV', 'West-Vlaanderen')"
        );
        /*Bulgaria*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('BG', 'BG-01', 'Blagoevgrad')
              , ('BG', 'BG-02', 'Burgas')
              , ('BG', 'BG-08', 'Dobrich')
              , ('BG', 'BG-07', 'Gabrovo')
              , ('BG', 'BG-26', 'Haskovo')
              , ('BG', 'BG-09', 'Kardzhali')
              , ('BG', 'BG-10', 'Kyustendil')
              , ('BG', 'BG-11', 'Lovech')
              , ('BG', 'BG-12', 'Montana')
              , ('BG', 'BG-13', 'Pazardzhik')
              , ('BG', 'BG-14', 'Pernik')
              , ('BG', 'BG-15', 'Pleven')
              , ('BG', 'BG-16', 'Plovdiv')
              , ('BG', 'BG-17', 'Razgrad')
              , ('BG', 'BG-18', 'Ruse')
              , ('BG', 'BG-27', 'Shumen')
              , ('BG', 'BG-19', 'Silistra')
              , ('BG', 'BG-20', 'Sliven')
              , ('BG', 'BG-21', 'Smolyan')
              , ('BG', 'BG-23', 'Sofia')
              , ('BG', 'BG-22', 'Sofia (stolitsa)')
              , ('BG', 'BG-24', 'Stara Zagora')
              , ('BG', 'BG-25', 'Targovishte')
              , ('BG', 'BG-03', 'Varna')
              , ('BG', 'BG-04', 'Veliko Tarnovo')
              , ('BG', 'BG-05', 'Vidin')
              , ('BG', 'BG-06', 'Vratsa')
              , ('BG', 'BG-28', 'Yambol')"
        );
        /*Cypros*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('CY', 'CY-04', 'Famagusta')
              , ('CY', 'CY-06', 'Kyrenia')
              , ('CY', 'CY-03', 'Larnaca')
              , ('CY', 'CY-01', 'Nicosia')
              , ('CY', 'CY-02', 'Limassol')
              , ('CY', 'CY-05', 'Paphos')"
        );
        /*Czechia*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('CZ', 'CZ-31', 'South Bohemia')
              , ('CZ', 'CZ-64', 'South Moravia')
              , ('CZ', 'CZ-41', 'Karlovy Vary')
              , ('CZ', 'CZ-52', 'Hradec Králové')
              , ('CZ', 'CZ-51', 'Liberec')
              , ('CZ', 'CZ-80', 'Moravia-Silesia')
              , ('CZ', 'CZ-71', 'Olomouc')
              , ('CZ', 'CZ-53', 'Pardubice')
              , ('CZ', 'CZ-32', 'Plzeň')
              , ('CZ', 'CZ-10', 'Prague')
              , ('CZ', 'CZ-20', 'Central Bohemia')
              , ('CZ', 'CZ-42', 'Ústí nad Labem')
              , ('CZ', 'CZ-63', 'Vysočina')
              , ('CZ', 'CZ-72', 'Zlín')"
        );
        /*Denmark*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('DK', 'DK-84', 'Capital Region of Denmark')
              , ('DK', 'DK-82', 'Central Denmark Region')
              , ('DK', 'DK-81', 'North Denmark Region')
              , ('DK', 'DK-85', 'Region Zealand')
              , ('DK', 'DK-83', 'Region of Southern Denmark')"
        );
        /*United Kingdom*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('GB', 'GB-ENG', 'England')
              , ('GB', 'GB-NIR', 'Northern Ireland')
              , ('GB', 'GB-SCT', 'Scotland')
              , ('GB', 'GB-WLS', 'Wales')"
        );
        /*Greece*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('GR', 'GR-A', 'Eastern Macedonia and Thrace')
              , ('GR', 'GR-I', 'Attica')
              , ('GR', 'GR-G', 'Western Greece')
              , ('GR', 'GR-C', 'Western Macedonia')
              , ('GR', 'GR-F', 'Ionian Islands')
              , ('GR', 'GR-D', 'Epirus')
              , ('GR', 'GR-B', 'Central Macedonia')
              , ('GR', 'GR-M', 'Crete')
              , ('GR', 'GR-L', 'Southern Aegean')
              , ('GR', 'GR-J', 'Peloponnese')
              , ('GR', 'GR-H', 'Central Greece')
              , ('GR', 'GR-E', 'Thessaly')
              , ('GR', 'GR-K', 'Northern Aegean')"
        );
        /*Croatia*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cCode`, `cName`)
            VALUES
                ('HR', 'HR-21', 'Zagreb City')
              , ('HR', 'HR-07', 'Bjelovar-Bilogora')
              , ('HR', 'HR-12', 'Brod-Posavina')
              , ('HR', 'HR-19', 'Dubrovnik-Neretva')
              , ('HR', 'HR-18', 'Istria')
              , ('HR', 'HR-04', 'Karlovac')
              , ('HR', 'HR-06', 'Koprivnica-Križevci')
              , ('HR', 'HR-02', 'Krapina-Zagorje')
              , ('HR', 'HR-09', 'Lika-Senj')
              , ('HR', 'HR-20', 'Međimurje')
              , ('HR', 'HR-14', 'Osijek-Baranja')
              , ('HR', 'HR-11', 'Požega-Slavonia')
              , ('HR', 'HR-08', 'Primorje-Gorski Kotar')
              , ('HR', 'HR-03', 'Sisak-Moslavina')
              , ('HR', 'HR-17', 'Split-Dalmatia')
              , ('HR', 'HR-15', 'Šibenik-Knin')
              , ('HR', 'HR-05', 'Varaždin')
              , ('HR', 'HR-10', 'Virovitica-Podravina')
              , ('HR', 'HR-16', 'Vukovar-Srijem')
              , ('HR', 'HR-13', 'Zadar')
              , ('HR', 'HR-01', 'Zagreb County')"
        );
        /*China*/
        $this->execute(
            "INSERT INTO
                `tstaat`(`cLandIso`, `cName`, `cCode`)
            VALUES
                ('CN', 'Beijing, 北京 (Běijīng)', 'CN-11')
              , ('CN', 'Tianjin, 天津 (Tiānjīn)', 'CN-12')
              , ('CN', 'Hebei, 河北 (Héběi)', 'CN-13')
              , ('CN', 'Shanxi, 山西 (Shānxī)', 'CN-14')
              , ('CN', 'Inner Mongolia, 内蒙古 (Nèi Ménggǔ)', 'CN-15')
              , ('CN', 'Liaoning, 辽宁 (Liáoníng)', 'CN-21')
              , ('CN', 'Jilin, 吉林 (Jílín)', 'CN-22')
              , ('CN', 'Heilongjiang, 黑龙江 (Hēilóngjiāng)', 'CN-23')
              , ('CN', 'Shanghai, 上海 (Shànghǎi)', 'CN-31')
              , ('CN', 'Jiangsu, 江苏 (Jiāngsū)', 'CN-32')
              , ('CN', 'Zhejiang, 浙江 (Zhèjiāng)', 'CN-33')
              , ('CN', 'Anhui, 安徽 (Ānhuī)', 'CN-34')
              , ('CN', 'Fujian, 福建 (Fújiàn)', 'CN-35')
              , ('CN', 'Jiangxi, 江西 (Jiāngxī)', 'CN-36')
              , ('CN', 'Shandong, 山东 (Shāndōng)', 'CN-37')
              , ('CN', 'Henan, 河南 (Hénán)', 'CN-41')
              , ('CN', 'Hubei, 湖北 (Húběi)', 'CN-42')
              , ('CN', 'Hunan, 湖南 (Húnán)', 'CN-43')
              , ('CN', 'Guangdong, 广东 (Guǎngdōng)', 'CN-44')
              , ('CN', 'Guangxi, 广西 (Guǎngxī)', 'CN-45')
              , ('CN', 'Hainan, 海南 (Hǎinán)', 'CN-46')
              , ('CN', 'Chongqing, 重庆 (Chóngqìng)', 'CN-50')
              , ('CN', 'Sichuan, 四川 (Sìchuān)', 'CN-51')
              , ('CN', 'Guizhou, 贵州 (Guìzhōu)', 'CN-52')
              , ('CN', 'Yunnan, 云南 (Yúnnán)', 'CN-53')
              , ('CN', 'Tibet, 西藏 (Xīzàng)', 'CN-54')
              , ('CN', 'Shaanxi, 陕西 (Shǎnxī)', 'CN-61')
              , ('CN', 'Gansu, 甘肃 (Gānsù)', 'CN-62')
              , ('CN', 'Qinghai, 青海 (Qīnghǎi)', 'CN-63')
              , ('CN', 'Ningxia, 宁夏 (Níngxià)', 'CN-64')
              , ('CN', 'Xinjiang, 新疆 (Xīnjiāng)', 'CN-65')
              , ('CN', 'Taiwan, 台湾 (Táiwān)', 'CN-71')
              , ('CN', 'Hong Kong, 香港 (Xiānggǎng)', 'CN-91')
              , ('CN', 'Macao, 澳门 (Àomén)', 'CN-92')"
        );
    }

    /**
     * @inheritDoc
     */
    public function down()
    {
        $szSql = <<<SQL

DROP TABLE IF EXISTS `tstaat`;

CREATE TABLE IF NOT EXISTS `tstaat` (
      `kStaat` int(10) unsigned NOT NULL AUTO_INCREMENT
    , `cLandIso` varchar(2) NOT NULL
    , `cName` varchar(255) NOT NULL
    , `cCode` varchar(10) NOT NULL
    , PRIMARY KEY (`kStaat`)
    , KEY `cLandIso` (`cLandIso`)
    , KEY `cName` (`cName`)
    , KEY `cCode` (`cCode`)
);
/*let the appropiated client decide here, which charset is used*/

INSERT INTO
    `tstaat`(`kStaat`, `cLandIso`, `cName`, `cCode`)
VALUES
      (1,'US','Alabama','AL')
    , (2,'US','Alaska','AK')
    , (3,'US','American Samoa','AS')
    , (4,'US','Arizona','AZ')
    , (5,'US','Arkansas','AR')
    , (6,'US','Armed Forces Africa','AF')
    , (7,'US','Armed Forces Americas','AA')
    , (8,'US','Armed Forces Canada','AC')
    , (9,'US','Armed Forces Europe','AE')
    , (10,'US','Armed Forces Middle East','AM')
    , (11,'US','Armed Forces Pacific','AP')
    , (12,'US','California','CA')
    , (13,'US','Colorado','CO')
    , (14,'US','Connecticut','CT')
    , (15,'US','Delaware','DE')
    , (16,'US','District of Columbia','DC')
    , (17,'US','Federated States Of Micronesia','FM')
    , (18,'US','Florida','FL')
    , (19,'US','Georgia','GA')
    , (20,'US','Guam','GU')
    , (21,'US','Hawaii','HI')
    , (22,'US','Idaho','ID')
    , (23,'US','Illinois','IL')
    , (24,'US','Indiana','IN')
    , (25,'US','Iowa','IA')
    , (26,'US','Kansas','KS')
    , (27,'US','Kentucky','KY')
    , (28,'US','Louisiana','LA')
    , (29,'US','Louisiana','LA')
    , (30,'US','Maine','ME')
    , (31,'US','Marshall Islands','MH')
    , (32,'US','Maryland','MD')
    , (33,'US','Massachusetts','MA')
    , (34,'US','Michigan','MI')
    , (35,'US','Minnesota','MN')
    , (36,'US','Mississippi','MS')
    , (37,'US','Missouri','MO')
    , (38,'US','Montana','MT')
    , (39,'US','Nebraska','NE')
    , (40,'US','Nevada','NV')
    , (41,'US','New Hampshire','NH')
    , (42,'US','New Jersey','NJ')
    , (43,'US','New Mexico','NM')
    , (44,'US','New York','NY')
    , (45,'US','North Carolina','NC')
    , (46,'US','North Dakota','ND')
    , (47,'US','Northern Mariana Islands','MP')
    , (48,'US','Ohio','OH')
    , (49,'US','Oklahoma','OK')
    , (50,'US','Oregon','OR')
    , (51,'US','Palau','PW')
    , (52,'US','Pennsylvania','PA')
    , (53,'US','Puerto Rico','PR')
    , (54,'US','Rhode Island','RI')
    , (55,'US','South Carolina','SC')
    , (56,'US','South Dakota','SD')
    , (57,'US','Tennessee','TN')
    , (58,'US','Texas','TX')
    , (59,'US','Utah','UT')
    , (60,'US','Vermont','VT')
    , (61,'US','Virgin Islands','VI')
    , (62,'US','Virginia','VA')
    , (63,'US','Washington','WA')
    , (64,'US','West Virginia','WV')
    , (65,'US','Wisconsin','WI')
    , (66,'US','Wyoming','WY')
    , (67,'CA','Alberta','AB')
    , (68,'CA','British Columbia','BC')
    , (69,'CA','Manitoba','MB')
    , (70,'CA','Newfoundland and Labrador','NL')
    , (71,'CA','New Brunswick','NB')
    , (72,'CA','Nova Scotia','NS')
    , (73,'CA','Northwest Territories','NT')
    , (74,'CA','Nunavut','NU')
    , (75,'CA','Ontario','ON')
    , (76,'CA','Prince Edward Island','PE')
    , (77,'CA','Quebec','QC')
    , (78,'CA','Saskatchewan','SK')
    , (79,'CA','Yukon Territory','YT')
    , (80,'DE','Niedersachsen','NDS')
    , (81,'DE','Baden-Württemberg','BAW')
    , (82,'DE','Bayern','BAY')
    , (83,'DE','Berlin','BER')
    , (84,'DE','Brandenburg','BRG')
    , (85,'DE','Bremen','BRE')
    , (86,'DE','Hamburg','HAM')
    , (87,'DE','Hessen','HES')
    , (88,'DE','Mecklenburg-Vorpommern','MEC')
    , (89,'DE','Nordrhein-Westfalen','NRW')
    , (90,'DE','Rheinland-Pfalz','RHE')
    , (91,'DE','Saarland','SAR')
    , (92,'DE','Sachsen','SAS')
    , (93,'DE','Sachsen-Anhalt','SAC')
    , (94,'DE','Schleswig-Holstein','SCN')
    , (95,'DE','Thüringen','THE')
    , (96,'AT','Wien','WI')
    , (97,'AT','Niederösterreich','NO')
    , (98,'AT','Oberösterreich','OO')
    , (99,'AT','Salzburg','SB')
    , (100,'AT','Kärnten','KN')
    , (101,'AT','Steiermark','ST')
    , (102,'AT','Tirol','TI')
    , (103,'AT','Burgenland','BL')
    , (104,'AT','Voralberg','VB')
    , (105,'CH','Aargau','AG')
    , (106,'CH','Appenzell Innerrhoden','AI')
    , (107,'CH','Appenzell Ausserrhoden','AR')
    , (108,'CH','Bern','BE')
    , (109,'CH','Basel-Landschaft','BL')
    , (110,'CH','Basel-Stadt','BS')
    , (111,'CH','Freiburg','FR')
    , (112,'CH','Genf','GE')
    , (113,'CH','Glarus','GL')
    , (114,'CH','Graubünden','GR')
    , (115,'CH','Jura','JU')
    , (116,'CH','Luzern','LU')
    , (117,'CH','Neuenburg','NE')
    , (118,'CH','Nidwalden','NW')
    , (119,'CH','Obwalden','OW')
    , (120,'CH','St. Gallen','SG')
    , (121,'CH','Schaffhausen','SH')
    , (122,'CH','Solothurn','SO')
    , (123,'CH','Schwyz','SZ')
    , (124,'CH','Thurgau','TG')
    , (125,'CH','Tessin','TI')
    , (126,'CH','Uri','UR')
    , (127,'CH','Waadt','VD')
    , (128,'CH','Wallis','VS')
    , (129,'CH','Zug','ZG')
    , (130,'CH','Zürich','ZH')
    , (131,'ES','A Coruña','A Coru?a')
    , (132,'ES','Alava','Alava')
    , (133,'ES','Albacete','Albacete')
    , (134,'ES','Alicante','Alicante')
    , (135,'ES','Almeria','Almeria')
    , (136,'ES','Asturias','Asturias')
    , (137,'ES','Avila','Avila')
    , (138,'ES','Badajoz','Badajoz')
    , (139,'ES','Baleares','Baleares')
    , (140,'ES','Barcelona','Barcelona')
    , (141,'ES','Burgos','Burgos')
    , (142,'ES','Caceres','Caceres')
    , (143,'ES','Cadiz','Cadiz')
    , (144,'ES','Cantabria','Cantabria')
    , (145,'ES','Castellon','Castellon')
    , (146,'ES','Ceuta','Ceuta')
    , (147,'ES','Ciudad Real','Ciudad Rea')
    , (148,'ES','Cordoba','Cordoba')
    , (149,'ES','Cuenca','Cuenca')
    , (150,'ES','Girona','Girona')
    , (151,'ES','Granada','Granada')
    , (152,'ES','Guadalajara','Guadalajar')
    , (153,'ES','Guipuzcoa','Guipuzcoa')
    , (154,'ES','Huelva','Huelva')
    , (155,'ES','Huesca','Huesca')
    , (156,'ES','Jaen','Jaen')
    , (157,'ES','La Rioja','La Rioja')
    , (158,'ES','Las Palmas','Las Palmas')
    , (159,'ES','Leon','Leon')
    , (160,'ES','Lleida','Lleida')
    , (161,'ES','Lugo','Lugo')
    , (162,'ES','Madrid','Madrid')
    , (163,'ES','Malaga','Malaga')
    , (164,'ES','Melilla','Melilla')
    , (165,'ES','Murcia','Murcia')
    , (166,'ES','Navarra','Navarra')
    , (167,'ES','Ourense','Ourense')
    , (168,'ES','Palencia','Palencia')
    , (169,'ES','Pontevedra','Pontevedra')
    , (170,'ES','Salamanca','Salamanca')
    , (171,'ES','Santa Cruz de Tenerife','Santa Cruz')
    , (172,'ES','Segovia','Segovia')
    , (173,'ES','Sevilla','Sevilla')
    , (174,'ES','Soria','Soria')
    , (175,'ES','Tarragona','Tarragona')
    , (176,'ES','Teruel','Teruel')
    , (177,'ES','Toledo','Toledo')
    , (178,'ES','Valencia','Valencia')
    , (179,'ES','Valladolid','Valladolid')
    , (180,'ES','Vizcaya','Vizcaya')
    , (181,'ES','Zamora','Zamora')
    , (182,'ES','Zaragoza','Zaragoza')
    , (183,'FR','Ain','1')
    , (184,'FR','Aisne','2')
    , (185,'FR','Allier','3')
    , (186,'FR','Alpes-de-Haute-Provence','4')
    , (187,'FR','Hautes-Alpes','5')
    , (188,'FR','Alpes-Maritimes','6')
    , (189,'FR','Ardèche','7')
    , (190,'FR','Ardennes','8')
    , (191,'FR','Ariège','9')
    , (192,'FR','Aube','10')
    , (193,'FR','Aude','11')
    , (194,'FR','Aveyron','12')
    , (195,'FR','Bouches-du-Rhône','13')
    , (196,'FR','Calvados','14')
    , (197,'FR','Cantal','15')
    , (198,'FR','Charente','16')
    , (199,'FR','Charente-Maritime','17')
    , (200,'FR','Cher','18')
    , (201,'FR','Corrèze','19')
    , (202,'FR','Corse-du-Sud','2A')
    , (203,'FR','Haute-Corse','2B')
    , (204,'FR','Côte-d\'Or','21')
    , (205,'FR','Côtes-d\'Armor','22')
    , (206,'FR','Creuse','23')
    , (207,'FR','Dordogne','24')
    , (208,'FR','Doubs','25')
    , (209,'FR','Drôme','26')
    , (210,'FR','Eure','27')
    , (211,'FR','Eure-et-Loir','28')
    , (212,'FR','Finistère','29')
    , (213,'FR','Gard','30')
    , (214,'FR','Haute-Garonne','31')
    , (215,'FR','Gers','32')
    , (216,'FR','Gironde','33')
    , (217,'FR','Hérault','34')
    , (218,'FR','Ille-et-Vilaine','35')
    , (219,'FR','Indre','36')
    , (220,'FR','Indre-et-Loire','37')
    , (221,'FR','Isère','38')
    , (222,'FR','Jura','39')
    , (223,'FR','Landes','40')
    , (224,'FR','Loir-et-Cher','41')
    , (225,'FR','Loire','42')
    , (226,'FR','Haute-Loire','43')
    , (227,'FR','Loire-Atlantique','44')
    , (228,'FR','Loiret','45')
    , (229,'FR','Lot','46')
    , (230,'FR','Lot-et-Garonne','47')
    , (231,'FR','Lozère','48')
    , (232,'FR','Maine-et-Loire','49')
    , (233,'FR','Manche','50')
    , (234,'FR','Marne','51')
    , (235,'FR','Haute-Marne','52')
    , (236,'FR','Mayenne','53')
    , (237,'FR','Meurthe-et-Moselle','54')
    , (238,'FR','Meuse','55')
    , (239,'FR','Morbihan','56')
    , (240,'FR','Moselle','57')
    , (241,'FR','Nièvre','58')
    , (242,'FR','Nord','59')
    , (243,'FR','Oise','60')
    , (244,'FR','Orne','61')
    , (245,'FR','Pas-de-Calais','62')
    , (246,'FR','Puy-de-Dôme','63')
    , (247,'FR','Pyrénées-Atlantiques','64')
    , (248,'FR','Hautes-Pyrénées','65')
    , (249,'FR','Pyrénées-Orientales','66')
    , (250,'FR','Bas-Rhin','67')
    , (251,'FR','Haut-Rhin','68')
    , (252,'FR','Rhône','69')
    , (253,'FR','Haute-Saône','70')
    , (254,'FR','Saône-et-Loire','71')
    , (255,'FR','Sarthe','72')
    , (256,'FR','Savoie','73')
    , (257,'FR','Haute-Savoie','74')
    , (258,'FR','Paris','75')
    , (259,'FR','Seine-Maritime','76')
    , (260,'FR','Seine-et-Marne','77')
    , (261,'FR','Yvelines','78')
    , (262,'FR','Deux-Sèvres','79')
    , (263,'FR','Somme','80')
    , (264,'FR','Tarn','81')
    , (265,'FR','Tarn-et-Garonne','82')
    , (266,'FR','Var','83')
    , (267,'FR','Vaucluse','84')
    , (268,'FR','Vendée','85')
    , (269,'FR','Vienne','86')
    , (270,'FR','Haute-Vienne','87')
    , (271,'FR','Vosges','88')
    , (272,'FR','Yonne','89')
    , (273,'FR','Territoire-de-Belfort','90')
    , (274,'FR','Essonne','91')
    , (275,'FR','Hauts-de-Seine','92')
    , (276,'FR','Seine-Saint-Denis','93')
    , (277,'FR','Val-de-Marne','94')
    , (278,'FR','Val-d\'Oise','95')
    , (279,'RO','Alba','AB')
    , (280,'RO','Arad','AR')
    , (281,'RO','Arges','AG')
    , (282,'RO','Bacau','BC')
    , (283,'RO','Bihor','BH')
    , (284,'RO','Bistrita-Nasaud','BN')
    , (285,'RO','Botosani','BT')
    , (286,'RO','Brasov','BV')
    , (287,'RO','Braila','BR')
    , (288,'RO','Bucuresti','B')
    , (289,'RO','Buzau','BZ')
    , (290,'RO','Caras-Severin','CS')
    , (291,'RO','Calarasi','CL')
    , (292,'RO','Cluj','CJ')
    , (293,'RO','Constanta','CT')
    , (294,'RO','Covasna','CV')
    , (295,'RO','Dâmbovita','DB')
    , (296,'RO','Dolj','DJ')
    , (297,'RO','Galati','GL')
    , (298,'RO','Giurgiu','GR')
    , (299,'RO','Gorj','GJ')
    , (300,'RO','Harghita','HR')
    , (301,'RO','Hunedoara','HD')
    , (302,'RO','Ialomita','IL')
    , (303,'RO','Iasi','IS')
    , (304,'RO','Ilfov','IF')
    , (305,'RO','Maramures','MM')
    , (306,'RO','Mehedinti','MH')
    , (307,'RO','Mures','MS')
    , (308,'RO','Neamt','NT')
    , (309,'RO','Olt','OT')
    , (310,'RO','Prahova','PH')
    , (311,'RO','Satu-Mare','SM')
    , (312,'RO','Salaj','SJ')
    , (313,'RO','Sibiu','SB')
    , (314,'RO','Suceava','SV')
    , (315,'RO','Teleorman','TR')
    , (316,'RO','Timis','TM')
    , (317,'RO','Tulcea','TL')
    , (318,'RO','Vaslui','VS')
    , (319,'RO','Vâlcea','VL')
    , (320,'RO','Vrancea','VN')
    , (321,'FI','Lappi','Lappi')
    , (322,'FI','Pohjois-Pohjanmaa','Pohjois-Po')
    , (323,'FI','Kainuu','Kainuu')
    , (324,'FI','Pohjois-Karjala','Pohjois-Ka')
    , (325,'FI','Pohjois-Savo','Pohjois-Sa')
    , (326,'FI','Etelä-Savo','Etelä-Savo')
    , (327,'FI','Etelä-Pohjanmaa','Etelä-Pohj')
    , (328,'FI','Pohjanmaa','Pohjanmaa')
    , (329,'FI','Pirkanmaa','Pirkanmaa')
    , (330,'FI','Satakunta','Satakunta')
    , (331,'FI','Keski-Pohjanmaa','Keski-Pohj')
    , (332,'FI','Keski-Suomi','Keski-Suom')
    , (333,'FI','Varsinais-Suomi','Varsinais-')
    , (334,'FI','Etelä-Karjala','Etelä-Karj')
    , (335,'FI','Päijät-Häme','Päijät-Häm')
    , (336,'FI','Kanta-Häme','Kanta-Häme')
    , (337,'FI','Uusimaa','Uusimaa')
    , (338,'FI','Itä-Uusimaa','Itä-Uusima')
    , (339,'FI','Kymenlaakso','Kymenlaaks')
    , (340,'FI','Ahvenanmaa','Ahvenanmaa')
    , (341,'EE','Harjumaa','EE-37')
    , (342,'EE','Hiiumaa','EE-39')
    , (343,'EE','Ida-Virumaa','EE-44')
    , (344,'EE','Jõgevamaa','EE-49')
    , (345,'EE','Järvamaa','EE-51')
    , (346,'EE','Läänemaa','EE-57')
    , (347,'EE','Lääne-Virumaa','EE-59')
    , (348,'EE','Põlvamaa','EE-65')
    , (349,'EE','Pärnumaa','EE-67')
    , (350,'EE','Raplamaa','EE-70')
    , (351,'EE','Saaremaa','EE-74')
    , (352,'EE','Tartumaa','EE-78')
    , (353,'EE','Valgamaa','EE-82')
    , (354,'EE','Viljandimaa','EE-84')
    , (355,'EE','Võrumaa','EE-86')
    , (356,'LV','Daugavpils','LV-DGV')
    , (357,'LV','Jelgava','LV-JEL')
    , (358,'LV','Jekabpils','Jekabpils')
    , (359,'LV','Jurmala','LV-JUR')
    , (360,'LV','Liepaja','LV-LPX')
    , (361,'LV','Liepajas novads','LV-LE')
    , (362,'LV','Rezekne','LV-REZ')
    , (363,'LV','Riga','LV-RIX')
    , (364,'LV','Rigas novads','LV-RI')
    , (365,'LV','Valmiera','Valmiera')
    , (366,'LV','Ventspils','LV-VEN')
    , (367,'LV','Aglonas novads','Aglonas no')
    , (368,'LV','Aizkraukles novads','LV-AI')
    , (369,'LV','Aizputes novads','Aizputes n')
    , (370,'LV','Aknistes novads','Aknistes n')
    , (371,'LV','Alojas novads','Alojas nov')
    , (372,'LV','Alsungas novads','Alsungas n')
    , (373,'LV','Aluksnes novads','LV-AL')
    , (374,'LV','Amatas novads','Amatas nov')
    , (375,'LV','Apes novads','Apes novad')
    , (376,'LV','Auces novads','Auces nova')
    , (377,'LV','Babites novads','Babites no')
    , (378,'LV','Baldones novads','Baldones n')
    , (379,'LV','Baltinavas novads','Baltinavas')
    , (380,'LV','Balvu novads','LV-BL')
    , (381,'LV','Bauskas novads','LV-BU')
    , (382,'LV','Beverinas novads','Beverinas ')
    , (383,'LV','Brocenu novads','Brocenu no')
    , (384,'LV','Burtnieku novads','Burtnieku ')
    , (385,'LV','Carnikavas novads','Carnikavas')
    , (386,'LV','Cesvaines novads','Cesvaines ')
    , (387,'LV','Ciblas novads','Ciblas nov')
    , (388,'LV','Cesu novads','LV-CE')
    , (389,'LV','Dagdas novads','Dagdas nov')
    , (390,'LV','Daugavpils novads','LV-DA')
    , (391,'LV','Dobeles novads','LV-DO')
    , (392,'LV','Dundagas novads','Dundagas n')
    , (393,'LV','Durbes novads','Durbes nov')
    , (394,'LV','Engures novads','Engures no')
    , (395,'LV','Garkalnes novads','Garkalnes ')
    , (396,'LV','Grobinas novads','Grobinas n')
    , (397,'LV','Gulbenes novads','LV-GU')
    , (398,'LV','Iecavas novads','Iecavas no')
    , (399,'LV','Ikskiles novads','Ikskiles n')
    , (400,'LV','Ilukstes novads','Ilukstes n')
    , (401,'LV','Incukalna novads','Incukalna ')
    , (402,'LV','Jaunjelgavas novads','Jaunjelgav')
    , (403,'LV','Jaunpiebalgas novads','Jaunpiebal')
    , (404,'LV','Jaunpils novads','Jaunpils n')
    , (405,'LV','Jelgavas novads','LV-JL')
    , (406,'LV','Jekabpils novads','LV-JK')
    , (407,'LV','Kandavas novads','Kandavas n')
    , (408,'LV','Kokneses novads','Kokneses n')
    , (409,'LV','Krimuldas novads','Krimuldas ')
    , (410,'LV','Krustpils novads','Krustpils ')
    , (411,'LV','Kraslavas novads','LV-KR')
    , (412,'LV','Kuldigas novads','LV-KU')
    , (413,'LV','Karsavas novads','Karsavas n')
    , (414,'LV','Lielvardes novads','Lielvardes')
    , (415,'LV','Limbazu novads','LV-LM')
    , (416,'LV','Lubanas novads','Lubanas no')
    , (417,'LV','Ludzas novads','LV-LU')
    , (418,'LV','Ligatnes novads','Ligatnes n')
    , (419,'LV','Livanu novads','Livanu nov')
    , (420,'LV','Madonas novads','LV-MA')
    , (421,'LV','Mazsalacas novads','Mazsalacas')
    , (422,'LV','Malpils novads','Malpils no')
    , (423,'LV','Marupes novads','Marupes no')
    , (424,'LV','Nauksenu novads','Nauksenu n')
    , (425,'LV','Neretas novads','Neretas no')
    , (426,'LV','Nicas novads','Nicas nova')
    , (427,'LV','Ogres novads','LV-OG')
    , (428,'LV','Olaines novads','Olaines no')
    , (429,'LV','Ozolnieku novads','Ozolnieku ')
    , (430,'LV','Preilu novads','LV-PR')
    , (431,'LV','Priekules novads','Priekules ')
    , (432,'LV','Priekulu novads','Priekulu n')
    , (433,'LV','Pargaujas novads','Pargaujas ')
    , (434,'LV','Pavilostas novads','Pavilostas')
    , (435,'LV','Plavinu novads','Plavinu no')
    , (436,'LV','Raunas novads','Raunas nov')
    , (437,'LV','Riebinu novads','Riebinu no')
    , (438,'LV','Rojas novads','Rojas nova')
    , (439,'LV','Ropazu novads','Ropazu nov')
    , (440,'LV','Rucavas novads','Rucavas no')
    , (441,'LV','Rugaju novads','Rugaju nov')
    , (442,'LV','Rundales novads','Rundales n')
    , (443,'LV','Rezeknes novads','LV-RE')
    , (444,'LV','Rujienas novads','Rujienas n')
    , (445,'LV','Salacgrivas novads','Salacgriva')
    , (446,'LV','Salas novads','Salas nova')
    , (447,'LV','Salaspils novads','Salaspils ')
    , (448,'LV','Saldus novads','LV-SA')
    , (449,'LV','Saulkrastu novads','Saulkrastu')
    , (450,'LV','Siguldas novads','Siguldas n')
    , (451,'LV','Skrundas novads','Skrundas n')
    , (452,'LV','Skriveru novads','Skriveru n')
    , (453,'LV','Smiltenes novads','Smiltenes ')
    , (454,'LV','Stopinu novads','Stopinu no')
    , (455,'LV','Strencu novads','Strencu no')
    , (456,'LV','Sejas novads','Sejas nova')
    , (457,'LV','Talsu novads','LV-TA')
    , (458,'LV','Tukuma novads','LV-TU')
    , (459,'LV','Tervetes novads','Tervetes n')
    , (460,'LV','Vainodes novads','Vainodes n')
    , (461,'LV','Valkas novads','LV-VK')
    , (462,'LV','Valmieras novads','LV-VM')
    , (463,'LV','Varaklanu novads','Varaklanu ')
    , (464,'LV','Vecpiebalgas novads','Vecpiebalg')
    , (465,'LV','Vecumnieku novads','Vecumnieku')
    , (466,'LV','Ventspils novads','LV-VE')
    , (467,'LV','Viesites novads','Viesites n')
    , (468,'LV','Vilakas novads','Vilakas no')
    , (469,'LV','Vilanu novads','Vilanu nov')
    , (470,'LV','Varkavas novads','Varkavas n')
    , (471,'LV','Zilupes novads','Zilupes no')
    , (472,'LV','Adazu novads','Adazu nova')
    , (473,'LV','Erglu novads','Erglu nova')
    , (474,'LV','Keguma novads','Keguma nov')
    , (475,'LV','Kekavas novads','Kekavas no')
    , (476,'LT','Alytaus Apskritis','LT-AL')
    , (477,'LT','Kauno Apskritis','LT-KU')
    , (478,'LT','Klaipedos Apskritis','LT-KL')
    , (479,'LT','Marijampoles Apskritis','LT-MR')
    , (480,'LT','Panevezio Apskritis','LT-PN')
    , (481,'LT','siauliu Apskritis','LT-SA')
    , (482,'LT','Taurages Apskritis','LT-TA')
    , (483,'LT','Telsiu Apskritis','LT-TE')
    , (484,'LT','Utenos Apskritis','LT-UT')
    , (485,'LT','Vilniaus Apskritis','LT-VL')
    , (486,'FR','Französisch-Guayana','973')
SQL;

        $this->execute($szSql);
    }
}
