<?php

use JTL\Update\IMigration;
use JTL\Update\Migration;

/**
 * Class Migration_20210208144100
 */
class Migration_20210208144100 extends Migration implements IMigration
{
    protected $author      = 'mh';
    protected $description = 'Add settings log table';

    /**
     * @inheritDoc
     */
    public function up()
    {
        $this->execute(
            'CREATE TABLE IF NOT EXISTS `teinstellungenlog` (
                `kEinstellungenLog`     INT          NOT NULL AUTO_INCREMENT,
                `kAdminlogin`           INT          NOT NULL,
                `cEinstellungenName`    VARCHAR(255) NOT NULL,
                `cEinstellungenWertAlt` VARCHAR(255) NOT NULL,
                `cEinstellungenWertNeu` VARCHAR(255) NOT NULL,
                `dDatum`                DATETIME     NOT NULL,
                PRIMARY KEY (`kEinstellungenLog`),
                KEY (`cEinstellungenName`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;'
        );
        $this->execute(
            'CREATE TABLE IF NOT EXISTS `teinstellungen_default` (
              `kEinstellungenSektion` int(10) unsigned NOT NULL DEFAULT 0,
              `cName` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
              `cWert` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
              `cModulId` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
              KEY `kEinstellungenSektion` (`kEinstellungenSektion`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;'
        );
        $this->execute(
            "INSERT INTO `teinstellungen_default` VALUES (5,'artikeldetails_xselling_standard_anzeigen','Y',NULL),
            (5,'artikeldetails_xselling_kauf_anzeigen','Y',NULL),(5,'artikeldetails_xselling_kauf_anzahl','6',NULL),
            (5,'artikel_variationspreisanzeige','1',NULL),(5,'artikel_lagerbestandsanzeige','ampel',NULL),
            (5,'artikeldetails_uvp_anzeigen','Y',NULL),(5,'artikeldetails_hersteller_anzeigen','Y',NULL),
            (5,'artikeldetails_lieferstatus_anzeigen','N',NULL),(5,'artikeldetails_gewicht_anzeigen','Y',NULL),
            (1,'global_wunschliste_artikel_loeschen_nach_kauf','N',NULL),
            (5,'artikel_weitere_artikel_hersteller_anzeigen','Y',NULL),
            (5,'artikeldetails_attribute_anhaengen','Y',NULL),
            (5,'artikeldetails_rabattanzeige','4',NULL),
            (5,'artikeldetails_sonderpreisanzeige','2',NULL),
            (5,'artikeldetails_kategorie_anzeigen','Y',NULL),
            (5,'artikeldetails_tabs_nutzen','Y',NULL),
            (5,'artikeldetails_navi_blaettern','Y',NULL),(5,'sie_sparen_x_anzeigen','1',NULL),
            (5,'artikeldetails_canonicalurl_varkombikind','Y',NULL),(4,'suche_prio_anmerkung','0',NULL),
            (1,'global_versandermittlung_lieferdauer_anzeigen','N',NULL),
            (5,'artikeldetails_fragezumprodukt_anzeigen','P',NULL),
            (5,'artikeldetails_fragezumprodukt_email','',NULL),
            (5,'produktfrage_abfragen_anrede','N',NULL), (5,'produktfrage_abfragen_vorname','N',NULL),
            (5,'produktfrage_abfragen_nachname','N',NULL), (5,'produktfrage_abfragen_firma','N',NULL),
            (5,'produktfrage_abfragen_tel','N',NULL), (5,'produktfrage_abfragen_fax','N',NULL),
            (5,'produktfrage_abfragen_mobil','N',NULL),(5,'produktfrage_kopiekunde','N',NULL),
            (5,'produktfrage_sperre_minuten','1',NULL),(5,'produktfrage_abfragen_captcha','Y',NULL),
            (7,'warenkorb_warenkorb2pers_merge','P',NULL),(5,'benachrichtigung_nutzen','Y',NULL),
            (5,'benachrichtigung_abfragen_vorname','N',NULL),(5,'benachrichtigung_abfragen_nachname','N',NULL),
            (5,'benachrichtigung_sperre_minuten','2',NULL),(5,'benachrichtigung_abfragen_captcha','N',NULL),
            (4,'suche_prio_name','10',NULL),
            (4,'suche_prio_suchbegriffe','9',NULL),(4,'suche_prio_artikelnummer','8',NULL),
            (4,'suche_prio_kurzbeschreibung','7',NULL),
            (4,'suche_prio_beschreibung','6',NULL),(4,'suche_prio_ean','5',NULL),
            (4,'suche_min_zeichen','4',NULL),
            (4,'suche_sortierprio_name','10',NULL),(4,'suche_sortierprio_name_ab','9',NULL),
            (4,'suche_sortierprio_preis','8',NULL),(4,'suche_sortierprio_preis_ab','7',NULL),
            (4,'suche_sortierprio_ean','2',NULL),
            (4,'suche_sortierprio_erstelldatum','3',NULL),(4,'suche_sortierprio_artikelnummer','4',NULL),
            (4,'suche_sortierprio_gewicht','5',NULL),
            (4,'suche_max_treffer','300',NULL),(4,'artikeluebersicht_lagerbestandsanzeige','ampel',NULL),
            (4,'artikeluebersicht_artikelproseite','15',NULL),(4,'artikeluebersicht_artikelsortierung','100',NULL),
            (4,'artikeluebersicht_max_seitenzahl','9',NULL),(4,'artikeluebersicht_rabattanzeige','1',NULL),
            (4,'artikeluebersicht_sonderpreisanzeige','1',NULL),
            (100,'zahlungsart_nachnahme_min_bestellungen','0','za_nachnahme_jtl'),
            (101,'exportformate_equot','N',NULL),(100,'zahlungsart_kreditkarte_min','0','za_kreditkarte_jtl'),
            (100,'zahlungsart_kreditkarte_max','0','za_kreditkarte_jtl'),(110,'suchtrefferfilter_anzahl','0',NULL),
            (1,'global_versandkostenfrei_darstellung','M',NULL),(5,'artikeldetails_xselling_kauf_parent','N',NULL),
            (100,'zahlungsart_kreditkarte_min_bestellungen','0','za_kreditkarte_jtl'),
            (100,'zahlungsart_lastschrift_max','0','za_lastschrift_jtl'),
            (100,'zahlungsart_lastschrift_min','0','za_lastschrift_jtl'),(7,'warenkorbpers_nutzen','Y',NULL),
            (121,'auswahlassistent_allefragen','Y',NULL),(121,'auswahlassistent_anzahl_anzeigen','Y',NULL),
            (1,'global_lieferverzoegerung_anzeigen','Y',NULL),
            (100,'zahlungsart_lastschrift_min_bestellungen','0','za_lastschrift_jtl'),
            (9,'bilder_hintergrundfarbe','#ffffff',NULL),
            (9,'bilder_dateiformat','AUTO',NULL),(121,'auswahlassistent_nutzen','N',NULL),
            (121,'auswahlassistent_anzeigeformat','T',NULL),(8,'box_bestseller_anzahl_anzeige','3',NULL),
            (8,'box_bestseller_anzahl_basis','10',NULL),(104,'rss_bewertungen_beachten','Y',NULL),
            (8,'box_sonderangebote_anzahl_anzeige','2',NULL),(8,'box_neuimsortiment_anzahl_anzeige','3',NULL),
            (8,'box_neuimsortiment_alter_tage','31',NULL),(8,'box_topangebot_anzahl_anzeige','3',NULL),
            (104,'rss_news_beachten','Y',NULL),(8,'box_erscheinende_anzahl_anzeige','3',NULL),
            (9,'container_verwenden','N',NULL),(114,'sitemap_google_ping','N',NULL),
            (101,'exportformate_semikolon','N',NULL),(3,'email_methode','mail',NULL),
            (3,'email_sendmail_pfad','',NULL),(3,'email_smtp_hostname','',NULL),
            (3,'email_smtp_port','',NULL),(3,'email_smtp_auth','1',NULL),(3,'email_smtp_user','admin',NULL),
            (3,'email_smtp_pass','pass',NULL),(3,'email_master_absender','',NULL),
            (3,'email_master_absender_name','',NULL),(1,'global_merkmalwert_url_indexierung','N',NULL),
            (7,'bestellvorgang_artikelkurzbeschreibung','Y',NULL),(7,'bestellvorgang_artikelattribute','Y',NULL),
            (7,'bestellvorgang_artikelmerkmale','Y',NULL),(5,'artikeldetails_produktbundle_nutzen','N',NULL),
            (1,'artikel_artikelanzeigefilter','1',NULL),(1,'artikel_lagerampel_gruen','5',NULL),
            (1,'artikel_lagerampel_rot','0',NULL),(1,'artikel_ampel_lagernull_gruen','Y',NULL),
            (1,'global_preis0','N',NULL),(1,'artikeldetails_variationswertlager','2',NULL),
            (1,'global_versandfrei_anzeigen','Y',NULL),(1,'global_warenkorb_weiterleitung','N',NULL),
            (1,'kategorien_anzeigefilter','1',NULL),(1,'global_sichtbarkeit','1',NULL),
            (1,'global_kundenkonto_aktiv','S',NULL),(1,'kaufabwicklung_ssl_nutzen','N',NULL),
            (6,'shop_ustid_force_remote_check','Y',NULL),(1,'global_versandhinweis','zzgl',NULL),
            (1,'global_erscheinende_kaeuflich','N',NULL),(1,'global_zaehler_anzeigen','N',NULL),
            (1,'global_ust_auszeichnung','auto',NULL),(1,'global_fusszeilehinweis','',NULL),
            (1,'global_steuerpos_anzeigen','Y',NULL),(1,'wartungsmodus_aktiviert','N',NULL),
            (4,'articleoverview_pricerange_width','150',NULL),(112,'global_meta_publisher','',NULL),
            (112,'global_meta_copyright','',NULL),(112,'global_meta_title_anhaengen','N',NULL),
            (112,'global_meta_title_preis','Y',NULL),(112,'global_meta_keywords_laenge','',NULL),
            (102,'kontakt_abfragen_anrede','N',NULL),(102,'kontakt_abfragen_vorname','O',NULL),
            (102,'kontakt_abfragen_nachname','O',NULL),(102,'kontakt_abfragen_firma','N',NULL),
            (102,'kontakt_abfragen_tel','N',NULL),(102,'kontakt_abfragen_fax','N',NULL),
            (102,'kontakt_abfragen_mobil','N',NULL),(102,'kontakt_kopiekunde','N',NULL),
            (102,'kontakt_sperre_minuten','1',NULL),(102,'kontakt_abfragen_captcha','N',NULL),
            (6,'kundenregistrierung_abfragen_titel','N',NULL),(6,'kundenregistrierung_abfragen_anrede','N',NULL),
            (6,'kundenregistrierung_abfragen_adresszusatz','N',NULL),
            (6,'kundenregistrierung_abfragen_mobil','N',NULL),(6,'kundenregistrierung_abfragen_fax','N',NULL),
            (6,'kundenregistrierung_abfragen_tel','N',NULL),(6,'kundenregistrierung_abfragen_ustid','N',NULL),
            (6,'kundenregistrierung_abfragen_www','N',NULL),(6,'kundenregistrierung_abfragen_geburtstag','N',NULL),
            (6,'kundenregistrierung_passwortlaenge','8',NULL),(6,'kundenregistrierung_standardland','DE',NULL),
            (6,'kundenregistrierung_abfragen_bundesland','N',NULL),
            (6,'kundenregistrierung_nur_lieferlaender','Y',NULL),(6,'kundenregistrierung_abgleichen_plz','N',NULL),
            (6,'lieferadresse_abfragen_anrede','N',NULL),(6,'lieferadresse_abfragen_titel','O',NULL),
            (6,'lieferadresse_abfragen_adresszusatz','N',NULL),(6,'lieferadresse_abfragen_bundesland','N',NULL),
            (6,'lieferadresse_abfragen_tel','N',NULL),(6,'lieferadresse_abfragen_email','N',NULL),
            (6,'lieferadresse_abfragen_mobil','N',NULL),(6,'lieferadresse_abfragen_fax','N',NULL),
            (6,'lieferadresse_abfragen_standardland','DE',NULL),
            (100,'zahlungsart_rechnung_max','0','za_rechnung_jtl'),
            (100,'zahlungsart_rechnung_min','0','za_rechnung_jtl'),
            (119,'suchspecials_sortierung_inkuerzeverfuegbar','-1',NULL),
            (119,'suchspecials_sortierung_topangebote','-1',NULL),
            (119,'suchspecials_sortierung_neuimsortiment','-1',NULL),
            (2,'startseite_neuimsortiment_anzahl','0',NULL),(2,'startseite_neuimsortiment_sortnr','1',NULL),
            (2,'startseite_topangebote_anzahl','0',NULL),(2,'startseite_topangebote_sortnr','2',NULL),
            (2,'startseite_sonderangebote_anzahl','0',NULL),(2,'startseite_sonderangebote_sortnr','3',NULL),
            (2,'startseite_bestseller_anzahl','3',NULL),(2,'startseite_bestseller_sortnr','4',NULL),
            (7,'warenkorb_produktbilder_anzeigen','Y',NULL),(7,'warenkorb_versandermittlung_anzeigen','Y',NULL),
            (7,'warenkorb_kupon_anzeigen','Y',NULL),(7,'bestellvorgang_wrb_anzeigen','1',NULL),
            (7,'bestellvorgang_einzelpreise_anzeigen','Y',NULL),(7,'bestellvorgang_lieferstatus_anzeigen','N',NULL),
            (7,'bestellvorgang_unregistriert','Y',NULL),
            (100,'zahlungsart_rechnung_min_bestellungen','0','za_rechnung_jtl'),(104,'rss_wawiabgleich','Y',NULL),
            (7,'bestellabschluss_bestellnummer_praefix','',NULL),
            (7,'bestellabschluss_bestellnummer_anfangsnummer','0',NULL),
            (7,'bestellabschluss_bestellnummer_suffix','',NULL),(7,'bestellabschluss_runden5','0',NULL),
            (7,'bestellabschluss_spamschutz_nutzen','N',NULL),
            (100,'zahlungsart_nachnahme_max','0','za_nachnahme_jtl'),
            (119,'suchspecials_sortierung_topbewertet','-1',NULL),
            (100,'zahlungsart_ueberweisung_min_bestellungen','0','za_ueberweisung_jtl'),
            (100,'zahlungsart_ueberweisung_min','0','za_ueberweisung_jtl'),
            (100,'zahlungsart_ueberweisung_max','0','za_ueberweisung_jtl'),
            (107,'bewertungserinnerung_kundengruppen','',NULL),(4,'suche_prio_han','3',NULL),
            (101,'exportformate_preis_ueber_null','N',NULL),(101,'exportformate_lager_ueber_null','N',NULL),
            (100,'zahlungsart_nachnahme_min','0','za_nachnahme_jtl'),
            (119,'suchspecials_sortierung_sonderangebote','-1',NULL),(101,'exportformate_lieferland','',NULL),
            (101,'exportformate_beschreibung','N',NULL),(104,'rss_artikel_beachten','Y',NULL),
            (104,'rss_alterTage','',NULL),(9,'bilder_externe_bildschnittstelle','A',NULL),
            (109,'kundenfeld_anzeigen','Y',NULL),(9,'bilder_variation_namen','3',NULL),
            (9,'bilder_kategorie_namen','1',NULL),(9,'bilder_artikel_namen','2',NULL),
            (9,'bilder_jpg_quali','85',NULL),(9,'bilder_merkmalwert_klein_hoehe','150',NULL),
            (9,'bilder_merkmalwert_klein_breite','150',NULL),(9,'bilder_merkmalwert_normal_hoehe','400',NULL),
            (9,'bilder_merkmalwert_normal_breite','1200',NULL),(101,'exportformate_quot','N',NULL),
            (104,'rss_logoURL','',NULL),(9,'bilder_merkmal_klein_hoehe','200',NULL),
            (9,'bilder_merkmal_klein_breite','600',NULL),(9,'bilder_merkmal_normal_hoehe','400',NULL),
            (9,'bilder_merkmal_normal_breite','1200',NULL),(9,'bilder_hersteller_klein_hoehe','200',NULL),
            (9,'bilder_hersteller_klein_breite','600',NULL),(1,'systemlog_flag','330',NULL),
            (104,'rss_nutzen','Y',NULL),(104,'rss_titel','',NULL),(104,'rss_copyright','',NULL),
            (104,'rss_description','',NULL),(119,'suchspecials_sortierung_bestseller','-1',NULL),
            (5,'artikeldetails_artikelgewicht_anzeigen','Y',NULL),
            (5,'artikeldetails_artikelintervall_anzeigen','Y',NULL),
            (5,'artikeldetails_warenkorbmatrix_anzeige','N',NULL),
            (5,'artikeldetails_warenkorbmatrix_anzeigeformat','H',NULL),
            (5,'artikeldetails_warenkorbmatrix_lagerbeachten','Y',NULL),
            (5,'merkmale_anzeigen','Y',NULL),(5,'artikeldetails_vergleichsliste_anzeigen','Y',NULL),
            (5,'mediendatei_anzeigen','YM',NULL),(5,'artikeldetails_aehnlicheartikel_anzahl','10',NULL),
            (5,'artikeldetails_stueckliste_anzeigen','Y',NULL),(4,'suche_prio_isbn','4',NULL),
            (4,'suche_sortierprio_erscheinungsdatum','4',NULL),(4,'suche_sortierprio_bestseller','1',NULL),
            (4,'suche_sortierprio_bewertung','1',NULL),(4,'suche_ajax_anzahl','5',NULL),
            (4,'artikeluebersicht_hersteller_anzeigen','N',NULL),(4,'topbest_anzeigen','TopBest',NULL),
            (4,'artikeluebersicht_gewicht_anzeigen','Y',NULL),
            (4,'artikeluebersicht_artikelgewicht_anzeigen','Y',NULL),
            (4,'artikeluebersicht_bestseller_anzahl','3',''),
            (4,'artikeluebersicht_vergleichsliste_anzeigen','Y',NULL),
            (4,'artikeluebersicht_wunschzettel_anzeigen','Y',NULL),
            (4,'artikeluebersicht_artikelintervall_anzeigen','Y',NULL),
            (4,'artikeluebersicht_erw_darstellung','Y',NULL),
            (9,'bilder_hersteller_normal_hoehe','400',NULL),(9,'bilder_hersteller_normal_breite','1200',NULL),
            (9,'bilder_artikel_mini_hoehe','40',NULL),(9,'bilder_artikel_mini_breite','40',NULL),
            (9,'bilder_artikel_klein_hoehe','200',NULL),(9,'bilder_artikel_klein_breite','200',NULL),
            (9,'bilder_artikel_normal_hoehe','600',NULL),(9,'bilder_artikel_normal_breite','600',NULL),
            (9,'bilder_artikel_gross_hoehe','1200',NULL),(9,'bilder_artikel_gross_breite','1200',NULL),
            (9,'bilder_variationen_mini_hoehe','40',NULL),(9,'bilder_variationen_mini_breite','40',NULL),
            (9,'bilder_variationen_hoehe','600',NULL),(9,'bilder_variationen_breite','600',NULL),
            (9,'bilder_variationen_gross_hoehe','1200',NULL),(9,'bilder_variationen_gross_breite','1200',NULL),
            (9,'bilder_kategorien_hoehe','400',NULL),(9,'bilder_kategorien_breite','1200',NULL),
            (1,'global_bestseller_minanzahl','10',NULL),(8,'box_zuletztangesehen_anzahl','3',NULL),
            (8,'boxen_topbewertet_anzahl','3',NULL),(8,'boxen_topbewertet_basisanzahl','20',NULL),
            (8,'boxen_topbewertet_minsterne','3',NULL),(111,'blacklist_benutzen','N',NULL),
            (1,'global_versandklasse_anzeigen','Y',NULL),(1,'global_dezimaltrennzeichen_sonstigeangaben',',',NULL),
            (1,'global_versandermittlung_anzeigen','Y',NULL),(6,'kundenregistrierung_abfragen_firma','N',NULL),
            (4,'artikelubersicht_bestseller_gruppieren','N',''),(6,'shop_ustid','',NULL),
            (6,'shop_ustid_bzstpruefung','N',NULL),(110,'allgemein_weiterleitung','Y',NULL),
            (110,'allgemein_herstellerfilter_benutzen','Y',NULL),(5,'isbn_display','N',NULL),
            (110,'allgemein_suchspecialfilter_benutzen','Y',NULL),
            (110,'allgemein_kategoriefilter_benutzen','Y',NULL),(110,'kategoriefilter_anzeigen_als','KA',NULL),
            (110,'bewertungsfilter_benutzen','box',NULL),(124,'caching_activated','N',NULL),
            (110,'suchtrefferfilter_nutzen','Y',NULL),(110,'merkmalfilter_verwenden','box',NULL),
            (110,'merkmal_anzeigen_als','BT',NULL),(110,'merkmalfilter_maxmerkmale','0',NULL),
            (110,'merkmalfilter_maxmerkmalwerte','0',NULL),(110,'preisspannenfilter_benutzen','box',NULL),
            (110,'preisspannenfilter_spannen_ausblenden','Y',NULL),
            (110,'preisspannenfilter_anzeige_berechnung','A',NULL),(110,'hersteller_bild_anzeigen','Y',NULL),
            (110,'hersteller_beschreibung_anzeigen','Y',NULL),(110,'merkmalwert_bild_anzeigen','BT',NULL),
            (110,'merkmalwert_beschreibung_anzeigen','Y',NULL),(110,'kategorie_bild_anzeigen','Y',NULL),
            (110,'kategorie_beschreibung_anzeigen','Y',NULL),(110,'artikeluebersicht_bild_anzeigen','BT',NULL),
            (110,'unterkategorien_lvl2_anzeigen','Y',NULL),(110,'unterkategorien_beschreibung_anzeigen','Y',NULL),
            (114,'sitemap_seiten_anzeigen','Y',NULL),(114,'sitemap_kategorien_anzeigen','Y',NULL),
            (114,'sitemap_hersteller_anzeigen','N',NULL),(114,'sitemap_news_anzeigen','Y',NULL),
            (114,'sitemap_newskategorien_anzeigen','N',NULL),(114,'sitemap_livesuche_anzeigen','N',NULL),
            (114,'sitemap_googleimage_anzeigen','Y',NULL),(7,'warenkorb_xselling_anzeigen','Y',NULL),
            (7,'warenkorb_xselling_anzahl','3',NULL),(7,'bestellvorgang_kaufabwicklungsmethode','NO',NULL),
            (7,'bestellvorgang_unregneukundenkupon_zulassen','Y',NULL),
            (7,'bestellvorgang_versand_steuersatz','HS',NULL),(7,'bestellabschluss_abschlussseite','S',NULL),
            (113,'news_kategorie_unternewsanzeigen','Y',NULL),(113,'news_kommentare_anzahlprobesucher','0',NULL),
            (113,'news_kommentare_anzahlproseite','0',NULL),(113,'news_kommentare_freischalten','Y',NULL),
            (113,'news_anzahl_box','0',NULL),(113,'news_anzahl_content','0',NULL),
            (113,'news_kommentare_nutzen','Y',NULL),(113,'news_benutzen','Y',NULL),
            (107,'bewertung_anzeigen','N',NULL),(107,'bewertung_freischalten','Y',NULL),
            (107,'bewertung_anzahlseite','10',NULL),(107,'bewertung_hilfreich_anzeigen','Y',NULL),
            (107,'bewertungserinnerung_nutzen','Y',NULL),(107,'bewertungserinnerung_versandtage','3',NULL),
            (107,'bewertung_guthaben_nutzen','N',NULL),(107,'bewertung_stufe2_anzahlzeichen','120',NULL),
            (107,'bewertung_stufe1_guthaben','1',NULL),(107,'bewertung_stufe2_guthaben','2',NULL),
            (107,'bewertung_max_guthaben','10',NULL),(107,'bewertung_artikel_gekauft','N',NULL),
            (1,'admin_ckeditor_mode','N',NULL),(10,'sonstiges_gratisgeschenk_nutzen','Y',NULL),
            (10,'sonstiges_gratisgeschenk_anzahl','10',NULL),(10,'sonstiges_gratisgeschenk_sortierung','B',NULL),
            (10,'sonstiges_livesuche_all_top_count','3',NULL),(10,'sonstiges_livesuche_all_last_count','50',NULL),
            (4,'livesuche_max_ip_count','5',NULL),(8,'boxen_livesuche_count','10',NULL),
            (108,'newsletter_emailmethode','mail',NULL),(108,'newsletter_sendmailpfad','',NULL),
            (108,'newsletter_smtp_host','',NULL),(108,'newsletter_smtp_port','0',NULL),
            (108,'newsletter_smtp_authnutzen','1',NULL),(108,'newsletter_smtp_benutzer','',NULL),
            (108,'newsletter_smtp_pass','',NULL),(108,'newsletter_emailadresse','',NULL),
            (108,'newsletter_emailtest','',NULL),(108,'newsletter_emailabsender','',NULL),
            (108,'newsletter_doubleopt','A',NULL),(108,'newsletter_sicherheitscode','4',NULL),
            (105,'preisverlauf_anzeigen','N',NULL),(6,'kundenregistrierung_pflicht_vorname','Y',''),
            (105,'preisverlauf_anzahl_monate','0',NULL),(106,'vergleichsliste_anzahl','10',NULL),
            (106,'vergleichsliste_artikelnummer','0',NULL),(106,'vergleichsliste_hersteller','5',NULL),
            (106,'vergleichsliste_kurzbeschreibung','0',NULL),(106,'vergleichsliste_beschreibung','10',NULL),
            (106,'vergleichsliste_artikelgewicht','9',NULL),(106,'vergleichsliste_versandgewicht','0',NULL),
            (106,'vergleichsliste_variationen','10',NULL),(106,'vergleichsliste_merkmale','9',NULL),
            (106,'vergleichsliste_spaltengroesse','300',NULL),
            (106,'vergleichsliste_spaltengroesseattribut','300',NULL),(106,'vergleichsliste_target','popup',NULL),
            (1,'admin_login_logger_mode','1',NULL),(1,'global_wunschliste_weiterleitung','Y',NULL),
            (1,'global_wunschliste_anzeigen','Y',NULL),(1,'global_wunschliste_freunde_aktiv','Y',NULL),
            (1,'global_wunschliste_max_email','10',NULL),(8,'boxen_wunschzettel_anzahl','3',NULL),
            (8,'boxen_wunschzettel_bilder','Y',NULL),(1,'artikel_lagerampel_keinlager','2',NULL),
            (4,'suchfilter_anzeigen_ab','0',NULL),(6,'registrieren_captcha','N',NULL),
            (9,'bilder_konfiggruppe_klein_breite','600',NULL),(9,'bilder_konfiggruppe_klein_hoehe','200',NULL),
            (112,'global_meta_maxlaenge_title','69',NULL),(112,'global_meta_maxlaenge_description','156',NULL),
            (6,'kundenregistrierung_pruefen_ort','Y',''),(6,'kundenregistrierung_pruefen_name','N',''),
            (6,'kundenregistrierung_pruefen_zeit','Y',''),(6,'kundenregistrierung_pruefen_email','N',''),
            (5,'artikeldetails_variationskombikind_bildvorschau','Y',NULL),
            (1,'garbagecollector_wawiabgleich','Y',NULL),(6,'kundenregistrierung_abfragen_firmazusatz','N',''),
            (4,'artikelubersicht_topbest_anzahl','6',''),(5,'artikeldetails_lieferantenbestand_anzeigen','U',NULL),
            (4,'artikeluebersicht_lagerbestandanzeige_anzeigen','U',''),
            (100,'zahlungsart_lastschrift_bic_abfrage','O','za_lastschrift_jtl'),
            (100,'zahlungsart_lastschrift_kontoinhaber_abfrage','Y','za_lastschrift_jtl'),
            (114,'sitemap_varkombi_children_export','N',NULL),(3,'email_smtp_verschluesselung','',''),
            (108,'newsletter_smtp_verschluesselung','',''),(124,'caching_lifetime','86400',NULL),
            (124,'caching_redis_host','localhost',NULL),(124,'caching_redis_port','6379',NULL),
            (124,'caching_memcache_port','11211',NULL),(124,'caching_memcache_host','localhost',NULL),
            (124,'caching_types_disabled','',NULL),(125,'shop_logo','Nova-Logo.svg',NULL),
            (1,'redirect_save_404','Y',NULL),(114,'sitemap_insert_changefreq','Y',NULL),
            (114,'sitemap_insert_priority','Y',NULL),(114,'sitemap_insert_lastmod','Y',NULL),
            (124,'caching_method','file',NULL),(124,'caching_redis_db','0',NULL),
            (124,'caching_redis_pass','',NULL),(124,'caching_redis_persistent','N',NULL),
            (124,'caching_debug','N',NULL),(124,'caching_debug_method','echo',NULL),
            (1,'global_shopname','',NULL),(1,'global_cookie_lifetime','0',NULL),
            (1,'global_cookie_path','',NULL),(1,'global_cookie_domain','',NULL),
            (1,'global_cookie_secure','S',NULL),(1,'global_cookie_httponly','S',NULL),
            (7,'warenkorb_varianten_varikombi_anzeigen','Y',NULL),(114,'sitemap_wawiabgleich','Y',NULL),
            (5,'artikeldetails_abmessungen_anzeigen','N',NULL),
            (5,'artikeldetails_kurzbeschreibung_anzeigen','Y',NULL),
            (4,'artikeluebersicht_kurzbeschreibung_anzeigen','N',NULL),(4,'suche_fulltext','N',NULL),
            (113,'news_anzahl_uebersicht','10',NULL),(110,'category_filter_type','A',NULL),
            (110,'manufacturer_filter_type','A',NULL),(110,'search_special_filter_type','A',NULL),
            (4,'products_per_page_list','10,20,30,40,50',NULL),(5,'adr_hazard_display','N',NULL),
            (124,'caching_rediscluster_hosts','',NULL),(124,'caching_rediscluster_strategy','N',NULL),
            (1,'artikel_artikelanzeigefilter_seo','seo',NULL),(114,'sitemap_images_categories','N',NULL),
            (114,'sitemap_images_manufacturers','N',NULL),(114,'sitemap_images_newscategory_items','N',NULL),
            (114,'sitemap_images_news_items','N',NULL),(114,'sitemap_images_attributes','N',NULL),
            (100,'zahlungsart_lastschrift_kreditinstitut_abfrage','O','za_lastschrift_jtl'),
            (127,'ftp_header','FTP Verbindung',NULL),(127,'ftp_hostname','localhost',NULL),
            (127,'ftp_port','21',NULL),(127,'ftp_user','',NULL),(127,'ftp_pass','',NULL),
            (127,'ftp_ssl','N',NULL),(127,'ftp_path','/',NULL),(1,'global_cancellation_time','14',NULL),
            (5,'benachrichtigung_min_lagernd','0',NULL),(106,'vergleichsliste_verfuegbarkeit','7',NULL),
            (106,'vergleichsliste_lieferzeit','6',NULL),(128,'cron_freq','10',NULL),
            (108,'newsletter_active','N',NULL),(108,'newsletter_send_delay','1',NULL),
            (110,'configgroup_110_manufacturer_filter','Herstellerfilter',NULL),
            (110,'hersteller_anzeigen_als','T',NULL),(9,'bilder_hersteller_mini_breite','120',NULL),
            (9,'bilder_hersteller_mini_hoehe','40',NULL),(9,'bilder_hersteller_gross_breite','1800',NULL),
            (9,'bilder_hersteller_gross_hoehe','600',NULL),(9,'bilder_merkmal_mini_breite','120',NULL),
            (9,'bilder_merkmal_mini_hoehe','40',NULL),(9,'bilder_merkmal_gross_breite','1800',NULL),
            (9,'bilder_merkmal_gross_hoehe','600',NULL),(9,'bilder_merkmalwert_mini_breite','40',NULL),
            (9,'bilder_merkmalwert_mini_hoehe','40',NULL),(9,'bilder_merkmalwert_gross_breite','1800',NULL),
            (9,'bilder_merkmalwert_gross_hoehe','600',NULL),(9,'bilder_konfiggruppe_mini_breite','120',NULL),
            (9,'bilder_konfiggruppe_mini_hoehe','40',NULL),(9,'bilder_konfiggruppe_normal_breite','1200',NULL),
            (9,'bilder_konfiggruppe_normal_hoehe','400',NULL),(9,'bilder_konfiggruppe_gross_breite','1800',NULL),
            (9,'bilder_konfiggruppe_gross_hoehe','600',NULL),(9,'bilder_kategorien_mini_breite','120',NULL),
            (9,'bilder_kategorien_mini_hoehe','40',NULL),(9,'bilder_kategorien_gross_breite','1800',NULL),
            (9,'bilder_kategorien_gross_hoehe','600',NULL),(9,'bilder_kategorien_klein_breite','600',NULL),
            (9,'bilder_kategorien_klein_hoehe','200',NULL),(9,'bilder_variationen_klein_breite','200',NULL),
            (9,'bilder_variationen_klein_hoehe','200',NULL),(8,'box_erscheinende_anzahl_basis','10',NULL),
            (8,'box_sonderangebote_anzahl_basis','10',NULL),(8,'box_neuimsortiment_anzahl_basis','10',NULL),
            (8,'box_topangebot_anzahl_basis','10',NULL),(9,'bilder_hersteller_namen','1',NULL),
            (9,'bilder_merkmal_namen','1',NULL),(9,'bilder_merkmalwert_namen','1',NULL),
            (1,'global_cookie_samesite','S',NULL),(9,'bilder_news_mini_breite','120',NULL),
            (9,'bilder_news_mini_hoehe','40',NULL),(9,'bilder_news_klein_breite','600',NULL),
            (9,'bilder_news_klein_hoehe','200',NULL),(9,'bilder_news_normal_breite','1200',NULL),
            (9,'bilder_news_normal_hoehe','400',NULL),(9,'bilder_news_gross_breite','1800',NULL),
            (9,'bilder_news_gross_hoehe','600',NULL),(9,'bilder_newskategorie_mini_breite','120',NULL),
            (9,'bilder_newskategorie_mini_hoehe','40',NULL),(9,'bilder_newskategorie_klein_breite','600',NULL),
            (9,'bilder_newskategorie_klein_hoehe','200',NULL),(9,'bilder_newskategorie_normal_breite','1200',NULL),
            (9,'bilder_newskategorie_normal_hoehe','400',NULL),(9,'bilder_newskategorie_gross_breite','1800',NULL),
            (9,'bilder_newskategorie_gross_hoehe','600',NULL),(127,'fs_general_header','General',NULL),
            (127,'fs_adapter','local',NULL),(127,'fs_timeout','10',NULL),(127,'sftp_header','SFTP Verbindung',NULL),
            (127,'sftp_hostname','localhost',NULL),(127,'sftp_port','22',NULL),(127,'sftp_user','',NULL),
            (127,'sftp_pass','',NULL),(127,'sftp_privkey','',NULL),(127,'sftp_path','/',NULL),
            (4,'products_per_page_gallery','10,20,30,40,50',NULL),
            (4,'artikeluebersicht_anzahl_darstellung1','10',NULL),
            (4,'artikeluebersicht_anzahl_darstellung2','20',NULL),
            (4,'artikeluebersicht_erw_darstellung_stdansicht','2',NULL),
            (7,'general_child_item_bulk_pricing','N',NULL),(5,'gtin_display','always',NULL),
            (128,'cron_type','s2s',NULL),(110,'allgemein_availabilityfilter_benutzen','Y',NULL),
            (110,'configgroup_110_availability_filter','Verfügbarkeitsfilter',NULL),
            (129,'consent_manager_active','Y',NULL),(1,'global_wizard_done','N',NULL),
            (6,'kundenlogin_max_loginversuche','0',NULL),(107,'bewertung_sortierung','0',NULL),
            (6,'direct_advertising','N',NULL),(5,'upload_modul_limit','10',NULL),
            (129,'configgroup_129_consentmanager','Cache',NULL),(124,'configgroup_124_cache','Consent manager',NULL),
            (128,'configgroup_128_cron','Cron',NULL),(127,'configgroup_127_filesystem','Filesystem',NULL),
            (121,'configgroup_121_selectionwizard','Auswahlassistent',NULL),
            (129,'consent_manager_show_banner','1',NULL);"
        );
    }

    /**
     * @inheritDoc
     */
    public function down()
    {
        $this->execute('DROP TABLE IF EXISTS `teinstellungenlog`');
        $this->execute('DROP TABLE IF EXISTS `teinstellungen_default`');
    }
}
